### ISSUE TITLE
Database provider pattern with context

### ISSUE THREAD

**Issue by Aidurber** [Nozbe/WatermelonDB#11]
Hello!

I've just been reviewing the examples and I'm wondering why there isn't a database provider using React context?

Was this an architectural decision? 

If not, do you think the library would benefit from a provider? In my head it would just have a similar API to MobX or Redux providers, just to reduce the prop drilling and access to the database deep in the tree if needed:

```javascript
<DatabaseProvider database={database}>
  <App />
</DatabaseProvider>
```

The context would be consumed like: 
```javascript
@withDatabase
const Posts = ({posts}) => {
  return posts && posts.map(post => <li>{post.name}</li>)
}
 // or
const Posts = ({posts}) => {
  return posts && posts.map(post => <li>{post.name}</li>)
}

export default withDatabase(Posts);
```

Perhaps the withObservables could call:
```javascript
// rest of HoC
<Database.Consumer>
  {({database}) => (
   <Component database={database} {...props} />
  )}
</Database.Consumer>
```

Not 100% on the API.

**Comment by radex** [comment]
> I've just been reviewing the examples and I'm wondering why there isn't a database provider using React context?

No specific reason! We do use a context at Nozbe to provide the database to components deep in the tree. The reason why it's not part of 🍉 is a) we have one context for many global "services" (just something specific to our app), and b) Watermelon isn't actually React-dependent (withObservables is a separate package).

I think for most users an API like this:

```js
<DatabaseProvider adapter={adapter} modelClasses={[Post, Comment]}>
  ...
</Database>
```

or even:

```js
<SQLiteDatabaseProvider ...> ...
```

would make sense. This should be easy to implement, but someone in the community would have to be willing to implement it, add tests, and update the documentation. Also, this would have to be available on an import like `@nozbe/watermelondb/DatabaseProvider`, not in the main exports (so that react is not necessary as a dependency)

**Comment by radex** [comment]
One more thing. In this example:

```js
const Posts = ({posts}) => {
  return posts && posts.map(post => <li>{post.name}</li>)
}

export default withDatabase(Posts);
```

perhaps this is what you meant, but you'd still need `withObservables` to subscribe to a specific query of posts. Injecting database via context just gives you an easier ability to do so.

**Comment by radex** [comment]
@Aidurber Hey, did you end up using WatermelonDB more? If so, it would be great if you could contribute this improvement :)

**Comment by radex** [comment]
@Aidurber Understood! Don't apologize, and thanks for your interest! Let me know if you wanted to get hacking with Watermelon and had any specific troubles

**Comment by Aidurber** [comment]
@radex I've got to work on this, got a couple more tests I want to write tomorrow. Just one question regarding your feedback.
You're passing the adapter and the models to the provider, am I correct in assuming the provider will create the database?
If that's the case isn't there a possibility of a new Database instance being created on rerenders? Wouldn't it be safer to just pass the database instance?

**Comment by radex** [comment]
done
