### ISSUE TITLE
Return data from join table

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#1137]
I have a product table that I display in a FlatList, before the price was in this table, but now we separate and we need to join.

```
select products.*, price_list_items.* 
from products
inner join price_list_items 
on price_list_items.product_id = products.id 
and company_id = '...'
```

I put it as childreen and withObservables, but the performance dropped a lot:

```
const enhance = withObservables(['product'], ({ product }) => ({
  product: product.observe(),
  priceListItems: product.priceListItems.observe(),
}));
```

I also tried using experimentalJoinTables, but I have to fetch each product:

```
Q.experimentalJoinTables(['price_list_items'])

await product.priceListItems.fetch();
```

Fix me if I'm wrong, but when I fetch to get the 'price_list_item' of each product, is it doing a database query?

If so, for better performance it would be that it already brought this data from the 'price_list_item' through the join.

In the last case I could do it by unsafeSqlQuery, but I don't know if I could be missing some features like observables.

Is there a more practical way to bring join data together?

**Comment by radex** [comment]
The most practical way is what you're doing now. If you're concerned about performance, profile your app and make sure that DB work is to blame. If it is, see if adding an index to price_list_items.product_id helps. If not, make a single query for all price_list_items that match your product_ids (so you're down to just two queries). It is possible to make it all in a single query (using unsafeSqlQuery and unsafeFetchRaw), but you're missing on a lot of other features, I don't recommend it unless you actually need it.

Still, most of the time you'll see that performance issues are either due to mis-configuration (no indexing) or on React Native level (rendering items on the list that don't need to be seen yet)

**Comment by osvaldokalvaitir** [comment]
@radex so I already have an index in the price_list_items table:

```
    { name: 'product_id', type: 'string', isIndexed: true },
```

For now I found it faster to put experimentalJoinTables and in useEffect() to put fetch than to use observe().

It's not that slow, but you can see, when I block the code, the products appear instantly, if I enter the code it takes a little longer.

Thanks for the answer.
