### ISSUE TITLE
withObservables help

### ISSUE THREAD

**Issue by nicolas-rohricht** [Nozbe/WatermelonDB#1260]
Really need help with making a component reactive using withObservables.
Read the docs so many times and didn't get this working.

I really appreciate any help.

What I have:

1 -  A FlatList which is correctly showing my list of Items and it updates correctly when an item is added or removed (via local changes or sync).
2 - The list doesn't update if one of the items updates (only on sync). PS: yes, the sync is finishing with no errors.
3 - Saw that I need to make every item of the list reactive, this is what I'm trying to get working.

This is where I have my list...

```

import React, { memo } from 'react'
import { FlatList, Text } from 'react-native'


import withObservables from '@nozbe/with-observables'
import TsuItem from './TsuItem'
import { database } from '../../Db/db'

const TsuList = memo(({tsus, onPressEdit }) => {
 

  return (
    <FlatList 
      data={tsus} 
      style={{flex: 1}}
      keyExtractor={(item) => item.id}
      renderItem={({item}) => 
        <TsuItem 
          onPressEdit={onPressEdit} 
          tsu={item} 
         />
      } 
    />
  )
})
  
const enhance = withObservables([''], () => ({
  tsus: database.collections.get('tsus').query().observe()
}))

export default enhance(TsuList)
```

This is the item (removed the styles object to cleanup the code here)
```

import React from 'react'
import { Text, StyleSheet, View, Button } from 'react-native'

import withObservables from '@nozbe/with-observables'

const TsuItem = ({tsu, onPressEdit}) => {

  return (
    <View style={styles.wrapper}>
      <View style={styles.description}>
        <Text style={styles.tsuContent}>From: <Text style={styles.tsuNumber}>{tsu.from}</Text></Text>
        <Text style={styles.tsuContent, styles.tsuTo}>To: <Text style={styles.tsuNumber}>{tsu.to}</Text></Text>
      </View>
      <View style={styles.buttonsWrapper}>
        <Button title='Edit' onPress={() => onPressEdit(tsu)} />
        <Button onPress={() => tsu.deleteTsu()} title='Delete' color='#FE5834' />
      </View>
    </View>
  )
}

const enhance = withObservables(['tsu'], ({ tsu }) => tsu )
const EnhancedTsu = enhance(TsuItem)

export default TsuItem

```

If I replace `export default TsuItem` with `export default EnhancedTsu` I start to get an error: Value passed to withObservables doesn't appear to be observable

**Comment by davevilela** [comment]
how did you solve this? any update?

**Comment by Stophface** [comment]
@nicolas-rohricht I am having a similar trouble with database. I am not sure how to make the initialzed database available to the app. Upon very first App start, I initialize the database like this

```
 const adapter = new SQLiteAdapter({
        schema: Foo,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            console.log(`[Database]: Error on bundled database: .... Error: `, error);
        }
    });

    const databaseObject = new Database({
        adapter,
        modelClasses: [
            Foo,
            Bar,
            Cat,
            SomeTable,
        ],
    });
```


Then, I can pass it down via the context API, something like

```
<DatabaseProvider
    database={databaseObject} />
        <App />
<DatabasePovider />
```

However, these lines `const databaseObject = new Database({...` I only call once, upon _very first_ App start, when the user opens the App for the very first time. I do not need to initialize the `databaseObject` every time again. If I would do that, then I would overwrite the content the App adds to the database... Thus, I am not having a database object, because `const databaseObject = new Database({...` is never called. Because of that, there is not `databaseObject` I can pass to the `<DatabaseProvider database={databaseObject} />`. 

But how can my app access the database then? What did you save in your `import { database } from '../../Db/db'`?
