### ISSUE TITLE
[Doubt] - Can I use WatermelonDB as simple SQLite driver?

### ISSUE THREAD

**Issue by EduFrazao** [Nozbe/WatermelonDB#1272]
Hi folks. Can I use WatermelonDB as simple SQLite driver?
I have a project with very specific needs, and I don't need/want to use Object models, Migrations, Sync, etc.

I only need a simple (and very fast) SQLite driver to handle databases (more than one for this application).
I already tried [react-native-sqlite-storage] but its slow and have problems with large transactions (100k rows) for example.
Right now, i'm usin react-native-quick-sqlite that is very fast and simple, but it lacks the support for using async calls, causing blocks on JS Thread, and its a problem for large operations or when a UI issues dozens of database calls.

WatermelonDB docs explains that another thread is used for SQLite operations, and its exactly what I'm looking for, but I can't find at least for now, a way to execute simple querys using raw sql.

**Comment by radex** [comment]
It's not well-documented, but yes. You can use SQLiteAdapter from `@nozbe/watermelondb/adapters/sqlite` directly, and not use any other part of 🍉 as a pure, raw SQL adapter.

Do note that in JSI mode, all calls are currently blocking, only in non-JSI mode you get the asynchronous multi-threaded operation (again, currently - this will change in the future). Having said that, you should check both and use a Profiler to see if the database is really the problem. You might find that actually, it's the JS-Native bridge that's the problem and 🍉's JSI is MUCH faster, or your React code is a problem, and with a few tweaks you'll fix the real problem (instead of masking it).

**Comment by EduFrazao** [comment]
> It's not well-documented, but yes. You can use SQLiteAdapter from `@nozbe/watermelondb/adapters/sqlite` directly, and not use any other part of watermelon as a pure, raw SQL adapter.
> 
> Do note that in JSI mode, all calls are currently blocking, only in non-JSI mode you get the asynchronous multi-threaded operation (again, currently - this will change in the future). Having said that, you should check both and use a Profiler to see if the database is really the problem. You might find that actually, it's the JS-Native bridge that's the problem and watermelon's JSI is MUCH faster, or your React code is a problem, and with a few tweaks you'll fix the real problem (instead of masking it).

Thank you very mutch for your answer.
I'm already using a SQLite driver that runs over JSI (https://github.com/ospfranco/react-native-quick-sqlite) . Its really fast, but when I need to do some large operations (like persist 100k rows), it takes about 5 seconds, but freezes my UI, because any interaction with it will dispatch calls to the JavaScript thead and its busy with waiting the JSI calls to finish.

But as you say, with JSI mode enable, all calls will be blocking with the current implementation. (for now)
I've tried to implement an async method on that library, but I think that JSI is not thread safe, and jsi::Value for example throws assert errors when used for another thread for example. So, i'm stucked at the moment :D

**Comment by radex** [comment]
> but when I need to do some large operations (like persist 100k rows), it takes about 5 seconds

I haven't tested @ospfranco's library, but would not be surprised if 🍉's raw JSI adapter was a bit faster. I've *really* optimized it.

If you run default JavaScriptCore on iOS, then I have a wonderful hack that makes JSI on JSC a few times faster: https://github.com/Nozbe/WatermelonDB/blob/master/native/ios/WatermelonDB/JSLockPerfHack.mm

Seriously, if you haven't already, learn how to use a profiler (like Xcode's instruments) to SEE where time is spent. More likely than not, it's spent mostly not in sqlite, but in JSI bridging. You'll be thanking me for learning how to use that tool ;)

If you saw that it actually is spent in SQLite, then there's many SQL-level optimizations you can do (e.g. if you batch insert, it's MUCH better to remove all indices, insert, and then re-index the whole table).

There's one more thing you can do. Where's the 100k rows coming from? If this is the initial data coming from the server, then you may be in luck. If you can structure the data from server to be a JSON and avoid re-processing this in JS, then you can achieve some incredible speed with 🍉 JSI adapter's "Turbo" (https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/sqlite/index.js#L300). 

I'm very much interested in adding proper multithreading to 🍉 JSI adapter, but it's very tricky to get right, and in *most* circumstances (where you're not adding 100k rows or doing a very, very expensive query), it can be detrimental to overall system performance instead of helping, so it's also an API design challange.

**Comment by EduFrazao** [comment]
Very nice tips @radex. In fact I didn't debug the JSI bridging times yet, but sure I will sure do.
This 100k rows are an example of one of the use cases of this application.
This app serves as an "development platform". We describe views and in JSON, and the react native build the UI dinamically. Sometimes, as a dependency of for this dynamic UI's our users (or developers :)) define some remote datasources that are fetched and created as dynamic tables on SQLite. Later, our users can run querys on this data to complete their tasks. Most tables have few hundreds of rows, but some of them may have 50k, 120k rows.

We load this data as many times as our users asks to (they set for how many time this data are valid and need to be refetched). So, we delete this tables (and their index), and recreate everything.

Most of the time, this loads are done when our users load their tasks. With the tasks fetched, I can know all their dependencies, that includes this dynamic datasets. So, I run several promises that fetch and store each one of them.
I have total control of the backend (so I can change the JSON contract freely).

Wait for SQLite is not the main problem in fact. My problem is that UI becomes irresponsible. But as you pointed, maybe download, fetch a do some small transformations on this ammount of data on the JavaScript thread can also be a problem.
So your "Turbo" adapter seems a very good idea. Fetch, parse and persist all from native side.

Thank you again for this ideas, even when they are not directly related with WatermelonDB.
I will close this topic now!
