### ISSUE TITLE
sql.js adapter? 

### ISSUE THREAD

**Issue by nmeibergen** [Nozbe/WatermelonDB#1316]
My app uses quit some relatively complex SQL queries in order to work appropriately. As a result extending to the web using WatermelonDB would currently be very challenging using the LokiJS adapter. It would therefore be great to have SQL capabilities in the browser, something like an adapter for [sql.js](https://github.com/sql-js/sql.js/). 

Before diving deeper into this, I'd like to know the following:
- Would this be a desirable extension for WatermelonDB? If not, why not?
- Where would be the main technical difficulties in creating such adapter?

**Comment by radex** [comment]
@nmeibergen I'm somewhat skeptical about SQL on web for performance reasons (since WebSQL was killed). SQLite itself is amazing, of course, but to really shine, you need low-level filesystem access and locking APIs (which web lacks) to avoid loading the entire database to memory. There's some other issues too. Having said that, progress has been made over the past 2 years and I haven't benchmarked the latest and greatest in SQL-on-web recently.

Anyway, that's the reason why WatermelonDB doesn't currently have a SQL adapter on web. However, I'm not against building it - in fact, I'm strongly in favor!  We already support SQLite on iOS, Android, and in Node.js. Do read through `src/adapters/sqlite` and search for old issues and pull requests related to adapters. You should be able to see that adding an extra target to adapters/sqlite is pretty straightforward.

I'd be very excited to see it implemented. I'm not going to do it myself, as we don't currently have such needs. But for many people, it could be a better choice than LokiJS since it's the same database target. And maybe it turns out that wasm SQLite is starting to match or beat LokiJS's performance, and if that's the case, I'd be in favor of migrating towards that and eventually deprecating Loki.

**Comment by dhrn** [comment]
I'm also facing same, It would be great to see this getting implemented. 

IIRC, I can see more (5-10)x speed on queries when i compare with better-sqlite performance on large data (2 lakh rows)

**Comment by nmeibergen** [comment]
@radex Thanks for your feedback. Very good to know that such implementation is technically feasible. I expect to work on implementing this in the near future. Keep you posted on this.

**Comment by barbalex** [comment]
There is sqlite via wasm now: https://sqlite.org/wasm/doc/trunk/index.md

Would that be an option?

**Comment by nmeibergen** [comment]
That is indeed an option, in particular the newly introduced OPFS support. The difficulty here is however the limited interface provided by the base WASM project. I am currently working on creating an improved interface for the WASM and and adapter for Watermelon, see the discussion [here](https://github.com/Nozbe/WatermelonDB/discussions/1545).
