### ISSUE TITLE
Database updates not showing/reflecting in react components 

### ISSUE THREAD

**Issue by Jim-Blair** [Nozbe/WatermelonDB#1319]
I'm leaving this here just in case anyone faces a similar issue as I did.

I struggled with the above issue for about 16hrs trying to figure out what I was doing wrong only to realize that by default I had a habit of extending `PureComponent` instead of just the usual react `Component` and because of this, my components weren't updating as they should. Upon extending `Component`, everything now worked as they should.

**Comment by Stophface** [comment]
@Jim-Blair I am having a similar trouble with database. I am not sure how to make the initialzed database available to the app. Upon very first App start, I initialize the database like this

```
 const adapter = new SQLiteAdapter({
        schema: Foo,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            console.log(`[Database]: Error on bundled database: .... Error: `, error);
        }
    });

    const databaseObject = new Database({
        adapter,
        modelClasses: [
            Foo,
            Bar,
            Cat,
            SomeTable,
        ],
    });
```


Then, I can pass it down via the context API, something like

```
<DatabaseProvider
    database={databaseObject} />
        <App />
<DatabasePovider />
```

However, these lines `const databaseObject = new Database({...` I only call once, upon _very first_ App start, when the user opens the App for the very first time. I do not need to initialize the `databaseObject` every time again. If I would do that, then I would overwrite the content the App adds to the database... Thus, I am not having a database object, because `const databaseObject = new Database({...` is never called. Because of that, there is not `databaseObject` I can pass to the `<DatabaseProvider database={databaseObject} />`. 

But how can my app access the database then? Do you have any idea?

**Comment by Jim-Blair** [comment]
Hello @Stophface, I'm not sure if I have the wrong idea but from your message, my understanding is that you are having trouble reaching the database object.
If that is the case then I guess it would be in order to share my approach. I'm not sure if it is the right way to go about it but then I avoided using the `DatabaseProvider` and instead just created `const databaseObject = new Database({..})` in a separate file, I then exported it and call it wherever it is needed but usually withing a helper function.
