### ISSUE TITLE
Question: Memory management: When are records purged?

### ISSUE THREAD

**Issue by mfbx9da4** [Nozbe/WatermelonDB#1377]
When are records purged from the in memory cache? From reading the source code, as far as I can see, records are never purged from the in memory cache. 

Doesn't this mean in theory the record cache will keep growing until the in memory cache holds a full copy of the database? One of the primary reasons for using a local database vs a state library* is because we have too much data such that we don't want to hold it all in memory. Should I be concerned?

*By state library, I mean for example: Zustand+MMKV or jotai+AsyncStorage etc. Obviously, there are other benefits to Watermelon vs a state library e.g. Watermelon supports incremental reads, incremental writes, off-the-main-thread sorting and filtering.

**Comment by radex** [comment]
> records are never purged from the in memory cache.

This is correct

> One of the primary reasons for using a local database vs a state library* is because we have too much data such that we don't want to hold it all in memory. Should I be concerned?

The reason why this was never improved is because this just didn't come up as a **real world** problem, at least for [Nozbe](https://nozbe.com). The thing about mobile apps is they're relatively short lived, and so there just isn't enough time for junk to accumulate to the point that this is a problem.

If you measure the memory growth of your app and it turns out that for some reason (e.g. huge table rows) this isn't true for your app, you are more than welcome to send pull requests adding a cache purging mechanism. This shouldn't be awfully hard to implement TBH.

**Comment by radex** [comment]
> During initial sync, by the nature of how synchronize() works, it will populate the entire record cache with the entire local database

Use `Turbo Sync` for initial sync, this sidesteps this problem completely

> My wider concern is that, sync-pull-changes creates records in the in-memory cache even if they're not actively being queried and that is costly. How can I avoid doing that but still keep the observables up to date?

It sounds like you assume it's costly instead of having tested that in your use case it's costly. Like I said, yes this could be a problem in theory and definitely would be nice to improve, but for me, hasn't proven to be a problem in practice.

Incremental syncs tend to be small, so it's not a large issue. Initial sync is heavy, but there's Turbo sync for that.

**Comment by radex** [comment]
> How would you go about inserting raw data into the database but only creating models in the record cache where there are queries observing those records?

Okay, so when you put it like that it simplifies the possible solutions. One way would be to use `database.adapter` directly to interact with the database from JS but from raw JSON - sidestepping object creation and caching. You could also think about skipping https://github.com/Nozbe/WatermelonDB/blob/master/src/Database/index.js#L149 - but you have to be really careful about that. If you do so, you must ensure that the Model object isn't retained, isn't reused, and isn't in cache already, otherwise it's unsafe. BTW: if you want my help in implementation, email me
