### ISSUE TITLE
withObservables doesn't work with React 18

### ISSUE THREAD

**Issue by mattlewer** [Nozbe/WatermelonDB#1388]
I've created a blank project using:
`npx react-native init watermelonTest --template react-native-template-typescript`

Installed WatermelonDB, got a table functional with all CRUD operations following the documentation.

I'm now trying to use withObservables, however there is nothing found. I have tried to install the package separately, still nothing.

If I change the import in the below screenshot to `import withObservables from '@nozbe/with-observables'` as suggested in the docs, it still cannot be found. I have tried every different way of importing this however it just doesn't seem to exist?

<img width="1503" alt="Screenshot 2022-09-06 at 11 26 27" src="https://user-images.githubusercontent.com/42501880/188834611-743714e1-e6d2-45af-9098-815c94049a57.png">

**Comment by radex** [comment]
your imports are broken

**Comment by mattlewer** [comment]
> your imports are broken

Any guidance?

**Comment by mattlewer** [comment]
I am having to import using the following:
`import withObservables from '@nozbe/watermelondb/node_modules/@nozbe/with-observables';`

The IDE complains 'is not a module' however, upon running the observing is working.

**Comment by skam22** [comment]
The error code is telling you that the resolver isn’t even looking in your node_modules folder for the dependency.  

Your import has a new line feed`\n` included in the path. 

Therefore your import was trying to look in the `\n\node_modules\*` path for the dependency instead of `node_modules`.

Make sure your IDE line feed settings are correct for your platform.  If they are already correct then the problem was with the copy/paste of the example code since the clipboard included /n. Just delete the line and retype it manually.
