### ISSUE TITLE
SQLite Version

### ISSUE THREAD

**Issue by CDBridger** [Nozbe/WatermelonDB#1433]
How would I go about upgrading the version of sqlite being used? I want to be able to use json_array and json_object in an unsafe raw query which is available in later versions of sqlite.

**Comment by radex** [comment]
@CDBridger Hey, I updated SQLite to latest version for 0.26 (not yet released), but this is only used on Android in JSI mode.

Happy to accept contributions so that you can choose custom version or build of SQLite in all modes and on all platforms, but it needs to be opt-in (this adds to build time and binary size and most people don't need this)
