### ISSUE TITLE
Sync erroneously creates/updates records that should delete in same sync pass

### ISSUE THREAD

**Issue by fivecar** [Nozbe/WatermelonDB#1462]
REPRO:

1. Run an app that uses WatermelonDB and syncs to a server
2. Create record "aaa"
3. Sync
4. Delete record "aaa"
5. Sync
6. Delete app from phone
7. Reinstall app
8. Sync

RESULT:
Record "aaa" syncs down, and doesn't get deleted.

REASON:
When you sync with the fresh (empty) DB, the server sends down a `SyncDatabaseChangeSet` that includes `aaa` in its `created` and `deleted` arrays. Yet `applyRemoteChanges` doesn't delete `aaa`, and instead only deletes records that were already in the DB prior to the sync in Step 8 (which, for a fresh install, is zero records).

I've got a fix coming.

**Comment by Dallas62** [comment]
Hi,

Don't see any issue in the described behaviour.
Must be an issue on your server sync process or an incorrect description of the issue.
You didn't delete any record on your exemple.
If you delete it, do not send it as created or updated.

**Comment by fivecar** [comment]
@Dallas62 : thanks for pointing out a mistake in my repro. I've edited it now to include the deletion step.

The way I implemented the server was simply to play back all the changes that the client sent up. Is that not correct? Are you saying that the server should, in addition to playing back everything that the client sent, also process logical operations like removing records in a sync that are both created and deleted?

If so, several of the sync implementations linked from WatermelonDB's documentation are wrong.

If you confirm the behavior above is actually the desired behavior, I'll submit a PR to augment the documentation. I do think that asking the server to do that form of logic (i.e. not only replay what the client has said the operations were, but to understand and intervene in the semantics of those operations) significantly complicates server logic (and creates a coupling between WatermelonDB's implementation and the server).

**Comment by Dallas62** [comment]
It's not clearly said in the documentation, few things:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/3429329/211044838-90419115-6790-4491-9185-6b6dea29c706.png">
- `dddd` is in deleted only
- `If lastPulledAt is null or 0, you MUST return all accessible records (first sync)` For me, `accessible` mean, at least, not deleted.

But it's not clear IMO.
Since they are deleted, there is no need to spam the client with useless data.

In my implementation, I delete the entity from the database and track the deletion in a dedicated table.

**Comment by fivecar** [comment]
@Dallas62 : two clarifications:

**1. Confirmation of Sent Data**
The particular case I'm puzzled by is slightly different than what you referenced in the documentation. Specifically, I'm curious when the server response looks like this:
```
{
  projects: {
    created: [{ id: "ddd", name: "Billy" }],
    updated: [],
    deleted: [ "ddd" ],
}
```
It seems to me this would be the expected output from the server, given the repro steps in this bug. LMK if I'm misunderstanding.

**2. What the Server Does**
You mentioned that your implementation deletes the entity from the database entirely. I had been preserving the record on the server (i.e. lazy deletion) so that the state of the DB can be restored between any two timestamps, but I'm guessing that's over-the-top unnecessary. If the client always wants changes up to the latest moment (which it currently seems like it does), then is it safe to delete records from the server and only keep the IDs of deleted records?

Thanks for your help in clarifying this!

**Comment by Dallas62** [comment]
For me the 1. is an error of implementation, this should not happen.

If you use lazy deletion (`deleted_at`), you should exclude all deleted elements with `deleted_at IS NULL`.

And ignore update if deleted.

The documentation doesn't mention locking the pull process if a push is in progress. Transaction works to preserve database integrity on server side, but without the rejection of the pull while a client is pushing changes, the `latest_pulled_at` might be upper than `created_at` or `updated_at` and exclude them from the client on next pull.

Lock must be specific to a `user` or `group`, not global. This case occurs only if there is multiple client on the same `user`.

Personally, I do not refer on mentioned implementations since they are not validated, not maintained and mostly still on `Initial commit`.

**Comment by fivecar** [comment]
@Dallas62 Really helpful clarifications. Thank you!

It makes complete sense. I've closed my PR, and will also update my implementation to not send create/update records for rows that will eventually be deleted.

>The documentation doesn't mention locking the pull process if a push is in progress. Transaction works to preserve database integrity on server side, but without the rejection of the pull while a client is pushing changes, the latest_pulled_at might be upper than created_at or updated_at and exclude them from the client on next pull.

My server implementation doesn't use timestamps, but instead uses revision numbers for `latest_pulled_at`. IIUC, this should avoid the case you mentioned (e.g. even if pulls aren't locked when another push is in progress, the pull will never get a `latest_pulled_at` beyond the last transaction-protected change uploaded by a push).
