### ISSUE TITLE
How to query search in n - n relation?

### ISSUE THREAD

**Issue by alicja-mruk** [Nozbe/WatermelonDB#1472]
I want to perform 'search' but in n-n relation.

Having following models:

```
export default class Contact extends Model {
  static table = SchemaTable.CONTACTS;
  static associations = {
    [SchemaTable.CONTACT_ATTRIBUTES]: {
      type: 'has_many',
      foreignKey: 'contact_id',
    },
  };

  @lazy
  attributes = this.collections
    .get(SchemaTable.ATTRIBUTES)
    .query(Q.on(SchemaTable.CONTACT_ATTRIBUTES, 'contact_id', this.id));

  @children(SchemaTable.CONTACT_ATTRIBUTES) contactAttributes;

  @text('first_name') firstName!: string;
  @text('last_name') lastName!: string;
}
```
```
export default class Attribute extends Model {
  static table = SchemaTable.ATTRIBUTES;
  static associations = {
    [SchemaTable.CONTACT_ATTRIBUTES]: {
      type: 'has_many',
      foreignKey: 'attribute_id',
    },
  };

  @lazy
  contacts = this.collections
    .get(SchemaTable.CONTACTS)
    .query(Q.on(SchemaTable.CONTACT_ATTRIBUTES, 'attribute_id', this.id));

  @text('key') key!: string;
  @text('value') value!: string;
  @text('type') type!: string;
}


```

```
export default class ContactAttribute extends Model {
  static table = SchemaTable.CONTACT_ATTRIBUTES;

  static associations = {
    [SchemaTable.ATTRIBUTES]: {type: 'belongs_to', key: 'attribute_id'},
    [SchemaTable.CONTACTS]: {type: 'belongs_to', key: 'contact_id'},
  };
  @immutableRelation(SchemaTable.CONTACTS, 'contact_id') contact!: Contact;
  @immutableRelation(SchemaTable.ATTRIBUTES, 'attribute_id')
  attribute!: Attribute;

  @text('contact_id') contactId!: string;
  @text('attribute_id') attributeId!: string;
  @text('attribute_value') attributeValue!: string;
}
```

Where `Contact` and `Attribute` are in n-n relation, I want to fetch only these contacts which have an attribute with value let's say 'Pet'. 

I tried this way:

```
const collection = await database
      .get<Contact>(SchemaTable.CONTACTS)
      .query(
        Q.experimentalJoinTables([
          SchemaTable.CONTACT_ATTRIBUTES,
        ]),
        Q.experimentalNestedJoin(
          SchemaTable.CONTACT_ATTRIBUTES,
          SchemaTable.ATTRIBUTES,
        ),

        Q.on(SchemaTable.ATTRIBUTES, 'value', 'Pet'),
      )
      .fetchCount();
```

but i get the message 
"Diagnostic error: Query on 'contacts' joins with 'attributes', but Contact does not have associations={} defined for 'attributes'"

Which makes sense, but I have no idea how to do it correctly. Can someone provide an example?

**Comment by scriptlabs** [comment]
As far as I see, @radex is not active anymore and 🍉 is very inactive and the set of features is extremely limited to the use-case of Nozbee, the task-planner app this db wrapper was made for.

To be honest, if you just started using 🍉 in your React-Native project, consider switching to a better maintained DB solution is my suggestion, as requesting features on watermelonDB will not give you any results soon.

The query feature is very very limited and most of the time you need to use dirty hacks or work-arrounds, for simple tasks.

While observable SQLite Data is a nice to have thing, maybe think about using your own SQLite implementation, or something like Realm or Firebase, where Realm is "reactive" too, using live objects.

We are currently switching to Realm too, because having a production app with 🍉 on board is a pain in the ass. 

Good luck

**Comment by alicja-mruk** [comment]
Can you guys answer my question? Is it even possible?
Also having these contacts, how to get for each of them the attribute_value field from that n-n relation? I can get only contact.attributes when I observe the changes but I also need the value for each of that attribute, simply saying merge tables attributes with contact_attribute

**Comment by radex** [comment]
@alicja-mruk if I understand your question correctly, this should work:

```js
const collection = await database
      .get<Contact>(SchemaTable.CONTACTS)
      .query(
        Q.experimentalJoinTables([
          SchemaTable.CONTACT_ATTRIBUTES,
        ]),
        Q.experimentalNestedJoin(
          SchemaTable.CONTACT_ATTRIBUTES,
          SchemaTable.ATTRIBUTES,
        ),
        Q.on(SchemaTable.CONTACT_ATTRIBUTES, Q.on(SchemaTable.ATTRIBUTES, 'value', 'Pet')),
      )
      .fetchCount();
```

In other words, fetch count of contacts that have a contact-attribute that has an attribute value=pet. Yes?

**Comment by alicja-mruk** [comment]
@radex I’ll try it, and let you know but thanks a lot

**Comment by scriptlabs** [comment]
@radex That‘s exactly what I was trying to say. 🍉 has a very nice functionallity when it comes to speed, lazy loading and string/number/boolean fields. The integration is rapid and easy, that‘s the reason why I gave it a try. But there are problems that others also mentioned in issues. And these wont get integrated or developed, because there is no roadmap for this and most issues end with, „you are welcome to contribute“. That‘s the way opensource works and you are absolutly right to answer like this, don‘t get me wrong… If I had the time and abilities to implement my requirements, a PR would be here. But, I need to „use a nice local db“ right now, not after contribution and features I have to implement myself that are a must have in my opinion for modern app databases. Like SUM, MAX, multiple relations to the same table with different names, and many more. I guess some are easy to implement, maybe I will give it a try. 🤓 Thank you

**Comment by radex** [comment]
@scriptlabs I understand you're frustrated because you're missing some features that, for your use, are a "must-have". But again, this isn't a paid service, it's an open source project you're free to use (and contribute back to). So why do you comment on an issue seemingly unrelated to your issues to discourage other folks from using 🍉?
