### ISSUE TITLE
Support for SQLite on web

### ISSUE THREAD

**Issue by danyf90** [Nozbe/WatermelonDB#1564]
Hello 👋 

As far as I understand, [on web WatermelonDB uses the LokiJS (and hence IndexedDB) adapter](https://watermelondb.dev/Implementation/Adapters.html?highlight=lokiJS#web).

Now that [SQLite WASM support has been released](https://sqlite.org/wasm/doc/trunk/index.md), would it be possible to use it in place of LokiJS?
If yes, would you expect it to bring performance improvements over the current solution?

Thanks 🙏

**Comment by radex** [comment]
See: https://github.com/Nozbe/WatermelonDB/discussions/1545

As for performance improvements, we'll see. Performance has more than one axis. I expect queries on large databases/complex queries would probably be faster. But initial load time for smallish databases could be worse due to large size of SQLite wasm to load
