### ISSUE TITLE
Seems like `isOptional: false` does not add constraint to table

### ISSUE THREAD

**Issue by 17Amir17** [Nozbe/WatermelonDB#1570]
I create a table with non-optional collumns, upon inspecting the schema with 
```sql
.schema "my_table"
```
I saw that there are no `NOT NULL` constraints on my fields and I was able to set them to null.
Looked around the code and it seems like we do not add the constraint at all, any reason for this?
```ts
// inside encodeSchema.js line 15
const encodeCreateTable = ({ name, columns }: TableSchema): SQL => {
  const columnsSQL = [standardColumns]
    .concat(Object.keys(columns).map((column) => `"${column}"`))
    .join(', ')
  return `create table "${name}" (${columnsSQL});`
}

```

**Comment by radex** [comment]
This is expected behavior, optionality affects Watermelon's behavior, but it's not enforced at SQLite level. Please note that SQLite doesn't have real types, so it doesn't enforce that something should be a string or a number either. Hence, I didn't see a point selectively deciding to enforce this (unless there is a performance reason for it).

Note that if you strongly wish for this, there's an API for modifying schema SQL
