### ISSUE TITLE
Any plans/chances for RN-Windows/UWP Support?

### ISSUE THREAD

**Issue by creambyemute** [Nozbe/WatermelonDB#178]
Hey there, 

WatermelonDB looks really promising. Unfortunately I can't make use of it (yet?) because our project has to support RN-Windows/UWP...

As it is based on SQLite, are there any chances on a plan to support RN-Windows at some point? https://github.com/andpor/react-native-sqlite-storage as well as https://github.com/craftzdog/react-native-sqlite-2 for example have support for SQLite on RN-Windows.

Cheers!

**Comment by creambyemute** [comment]
@radex Alright, just to ensure I got it correctly:
What basically has to be done would be the following (I haven't thoroughly dived in yet):

- Add native windows project to WatermelonDB (like iOS/ and android/ folder)
- Integrate the native windows SQLite package (`SQLite.Net.Interop` for UWP or `Microsoft.Data.Sqlite` for WPF)
- Implement the above mentioned classes and methods

I'm just trying to put together a list of tasks that have to be done and I may tackle this in some spare time. Did I miss anything?

**Comment by radex** [comment]
@creambyemute 

We still have to decide internally at @Nozbe whether we want to accept this into the core (since we wouldn't want to put our own efforts to maintain the Windows support), or whether it would be better to develop this adapter as an add-on package (in your own repo).

On one hand, it would be easier for everyone. On the other, if we make a change to common adapter code, and Windows code breaks CI, either we'd have to fix it ourselves, or wait for contributions.

cc @mobily @tkapelak @rozPierog 

I *think* your list is complete in terms of pure implementation, but it would be best for its quality to also integrate with CI. There's a full suite of common tests for adapters, but it requires a native project that can run on CI, open the simulator/app, run this index: https://github.com/Nozbe/WatermelonDB/blob/master/src/index.integrationTests.native.js — and report tests as OK or fail depending on the result. But you can skip this part if you just want this to work and want to test manually

**Comment by radex** [comment]
@creambyemute Hey, are you still interested in pursuing this issue?

**Comment by creambyemute** [comment]
@radex I'm atm busy finishing up our app, but later I'd be happy to tackle it.

**Comment by radex** [comment]
@creambyemute Alright, do let us know when you want to tackle this!

I think we'd prefer initially to have this as a separate repository for reasons described above, but if we start using it ourselves or there's enough interest from the community, we could merge it into the core.

**Comment by mlecoq** [comment]
Hi @radex, we are thinking on windows support for our app currently in development and we are looking at our dependencies to check if it looks doable. Is RN-Windows still considered at Nozbe or should we look at another solution as offline database for windows support ?

Thanks

**Comment by radex** [comment]
@mlecoq If you develop a RN-Windows adapter (with JSI, it should be very easy, since even native code is cross platform C++, just needs some hooks), then we can talk about either upstreaming it into the main WatermelonDB repository or sharing knowledge to make maintenance easy for both sides.

**Comment by mlecoq** [comment]
react-native-window support is mentioned here:

https://github.com/microsoft/react-native-windows/issues/7016
