### ISSUE TITLE
Reduce memory usage in destroy process

### ISSUE THREAD

**Issue by ieschalier** [Nozbe/WatermelonDB#186]
# Description

With example it must be more understandable. 

```
export default class List extends Model {
  static table = 'lists'

  static associations = {
    items: { type: 'has_many', foreignKey: 'list_id' },
  }

  @children('items')
  items

  destroyPermanently = async () => {
    await this.items.destroyAllPermanently()
    await super.destroyPermanently()
  }
}
```

In case of list with a lot of items, destroy List cause a peak of memory usage.

It must be a real problem in mobile because we have a limit of memory usage, after this limit app is killed by OS.

# Proposal

Actually `destroyAllPermanently` seems to fetch all items one by one and delete then one by one. I think this is done for simplify manage of watermelon cache.

Do you think it’s possible to delete with a single query to avoid this peak of memory ?

**Comment by radex** [comment]
> Do you think it’s possible to delete with a single query to avoid this peak of memory ?

It's possible, but not trivial. It's one of the TODO steps before 1.0. The problem is finding all dependencies (say, delete a project with all its tasks with all their comments), and then updating the JS state (removing all deleted items from local cache, notifying observers).

If you want to tackle this, or at least part of it, let me know — I'll give you pointers.

For quick workarounds, you could try chunking (fetch list.items, and then delete portions of the list in chunks), or you could try issuing a raw SQL query (https://github.com/Nozbe/WatermelonDB/issues/103)

**Comment by ieschalier** [comment]
Ok, we try with a raw SQL query and it's seems to work very well. Thanks for the tricks 🙂

I don’t have time in next 2 weeks but maybe after

**Comment by radex** [comment]
@ieschalier hey, what's the status of the issue for you?

**Comment by ieschalier** [comment]
Hey @radex, currently nobody in my team have time to work on this issue.

Usage of raw query do the job, but it's not the more pretty solution.

**Comment by radex** [comment]
Understood — thanks for the update!
