### ISSUE TITLE
How do I define a column to be unique?

### ISSUE THREAD

**Issue by NKlug** [Nozbe/WatermelonDB#198]
I'm wondering how I can specify a column to be `unique`. It would also be interesting how I can define another column, let's call it `name`, to be the primary key instead of the default `id` column.
I haven't found anything on this in the docu/repo.

Edit: Grammar

**Comment by maxammann** [comment]
This relates to: https://github.com/Nozbe/WatermelonDB/issues/36

It is not possible to prevent duplicates.

**Comment by radex** [comment]
@NKlug There's no such option at this moment. It kinda goes against Watermelon's approach of doing validation on JavaScript and avoiding database-side errors (since they're tricky to handle, when you use observables and such).

If you want to propose a solution to this problem, I'd be happy to take a look
