### ISSUE TITLE
Pass web worker reference to LokiJSAdapter

### ISSUE THREAD

**Issue by yatsyk** [Nozbe/WatermelonDB#204]
LokiJSAdapter assumes worker-loader and webpack presence for Web Worker loading. This makes WatermelonDB impossible to use with other bundlers such as parcel. It would be nice to have the possibility to pass started worker reference to adapter.

**Comment by yatsyk** [comment]
Cloned the repo and got error after running the tests:

```
.../WatermelonDB/src/__tests__/setup.js:40
    import { logger } from '../utils/common';
           ^

    SyntaxError: Unexpected token {
```
Looks like something wrong with babel setup. Does something should be installed globally which is not described in https://github.com/Nozbe/WatermelonDB/blob/master/CONTRIBUTING.md ?

**Comment by radex** [comment]
@yatsyk Not that I know of… I haven't had that break on me. The only global dependency I can think of is Node… Are you running v >=10?

**Comment by yatsyk** [comment]
@radex checked on just installed node v10.15.0, same error

**Comment by radex** [comment]
hey, check out https://github.com/Nozbe/WatermelonDB/pull/243 if you're still interested in contributing — hopefully all these changes will fix your test issues :)

**Comment by yatsyk** [comment]
Problem with test runner disappeared. It seems it was something wrong with node versions on my side. 

Stopped experimenting with WatermelonDB for some time so I’m not sure when I’ll be ready to prepare pull request. 

What if we use https://github.com/GoogleChromeLabs/comlink to communicate with worker. Comlink could communicate with any object with postMessage, addEventListener and removeEventListener methods defined. In this case we could pass Worker, ServiceWorker or adapter created in our process. I think that this architecture will be simpler than WorkerBridge/workerMock. 

What do you think?

**Comment by radex** [comment]
@yatsyk `comlink` looks nice, but I'd rather avoid it because it relies on ES6 Proxy. I'm not a huge fan of Proxy, because a) it hides stuff behind magic (I prefer explicitly defined interface via Flow/TS), and b) it requires a polyfill, adding 4KB for a simple thing...

I don't thinnk it's really necessary, is it?

https://github.com/Nozbe/WatermelonDB/blob/53b3357c6875a4be769fc107b179454febacd707/src/adapters/lokijs/WorkerBridge.js#L28 — this is the only line that needs configuration, really. As long as you pass here Worker-compatible object, it's all good
