### ISSUE TITLE
Demo URLs invalid

### ISSUE THREAD

**Issue by brandondrew** [Nozbe/WatermelonDB#205]
The URLs in the web demo all give a 404 error:

https://watermelondb.now.sh/blog/37shaoajdy6tgx35/post/m44q9yoc7q4t0bqj

They are generated when using the demo _if_ you visit from the demo's main URL, but those generated URLs are not valid for use _as URLs_.  You can't open the URL in a new browser window and get anywhere.

I don't know if this problem is limited to the demo, or whether it is a deeper problem.

**Comment by radex** [comment]
closing - @brandondrew let me know if you're interested in contributing, i can give you pointers as to how to fix the issue ;)

**Comment by brandondrew** [comment]
Sure, if you can give me pointers then it might be a good way to get started with 🍉

**Comment by radex** [comment]
@brandondrew Sure, take a look here:

https://github.com/Nozbe/WatermelonDB/blob/master/examples/web/src/components/Root/index.js#L2

the easy way out is to just replace the BrowserRouter with… MemoryRouter or something like that — check out the docs from react-router. But it's probably easy to modify ZEIT `now` settings (or web pack?) to accept URLs such as `https://watermelondb.now.sh/blog/37shaoajdy6tgx35/post/m44q9yoc7q4t0bqj`.

You can also tweak the styling (since it doesn't look super pretty right now) or add new small things to the demo if you want :)

**Comment by radex** [comment]
@brandondrew Hey, did you have a change to take a look at this?

**Comment by HiMrHu** [comment]
hi @radex I can help improve the problem, replace the BrowserRouter with the HashRouter, url will look  like `https://watermelondb.now.sh/#blog/37shaoajdy6tgx35/post/m44q9yoc7q4t0bqj`, i can PR fixing that.
