### ISSUE TITLE
database observable calls on every new record

### ISSUE THREAD

**Issue by namjul** [Nozbe/WatermelonDB#212]
I am trying to create some fake data and load initially.
But i am not able to get them working like in the example.
I that i have an enhanced component like so:

```javascript
const enhance = withObservables(null, ({ database }) => ({
  items: database.collections.get('items').query(),
}))
```
And load the data like so:
```javascript
const load = async () => {
  const count = await generate10k(database);
  alert(`Generated ${count} records!`);
}

load()
```
The enhanced component recieves the items but renders everytime a new item enters the database.
I use the same generate script as in the example.

![image](https://user-images.githubusercontent.com/328836/51437541-fd815480-1c9f-11e9-90d4-1dfd7a4fb0b5.png)

In the example it correctly renders only once. But when i move the generate call somewhere else like into the first `index.js`, it does also render the enhanced component with blogs everytime a new one is created. I trying to find out what the difference is but i just can't see it.

Also i noticed in my code i get `Database.batch() can only be called from inside of an Action. See docs for more details` but the example does not, even though its the same code and same versions.

**Comment by rkrajewski** [comment]
@namjul Just like the warning says, you should call `batch` inside `action`. 

```js
await database.action(async () => {
  await database.batch(...newModels)
})
```
where `newModels` is an array of models created with `collection.prepareCreate`.

**Comment by namjul** [comment]
Thats already happening inside the `generate10k` function. 
So my issue is even though i am using `batch` with `prepareCreate` the render function gets called for each item created. And it should only be called ones. In the [example](https://github.com/Nozbe/WatermelonDB/blob/master/examples/web/src/components/Root/index.js#L17) it works, but when i move the generate function outside, for example into [here](https://github.com/Nozbe/WatermelonDB/blob/master/examples/web/src/index.js) the [component](https://github.com/Nozbe/WatermelonDB/blob/master/examples/web/src/components/BlogList/index.js#L29) gets rendered for each new record.
Why is that?

**Comment by namjul** [comment]
Oh i see. I have a look into the PR. Thanks!

**Comment by namjul** [comment]
So i am at the point where this line https://github.com/Nozbe/WatermelonDB/pull/173/files#diff-c5500afe3b4153f17b1903a7ac03029dR125
causes this error: `Cannot observe uncommitted record`

What i understand is following:
Calling `this.changes.next` with all operations for each collection is what we are after.
But there are some additional things that need to happen for each record. I see marking as commited, caching and notifying. Are there already ideas how this has to be done?
I also see that seperating the call for updated and created records was also intended. What was the purpose behind that?

**Comment by radex** [comment]
@namjul Sorry for late reply!

Let's move this discussion in the PR thread, OK?

Let me show you how this works now:

1. When you do `prepareUpdate`, record is set as `hasPendingUpdate=true`. This is to prevent multiple changes before the change is committed (saved to database): https://github.com/Nozbe/WatermelonDB/blob/e7df835c7ba58c950d0f09564e831d7f350ff987/src/Model/index.js#L102
2. Similarly, when you do `Collection.prepareCreate`, this calls to Model._prepareCreate, and marks the record as `isCommited=false`: https://github.com/Nozbe/WatermelonDB/blob/e7df835c7ba58c950d0f09564e831d7f350ff987/src/Model/index.js#L192 — again, this will prevent updating , observing, etc. before you save to DB
3. When you pass those records into Database.batch: https://github.com/Nozbe/WatermelonDB/blob/e7df835c7ba58c950d0f09564e831d7f350ff987/src/Database/index.js#L49 — we push them to the adapter (low-level connection to database), and change hasPendingUpdate=false, isCommited=true 
4. When done, we notify observers of changes: https://github.com/Nozbe/WatermelonDB/blob/e7df835c7ba58c950d0f09564e831d7f350ff987/src/Collection/index.js#L125 - but it's done per-record.

Instead, it should be done per-collection, and instead of pushing onto `this.changes` a single `record` change (https://github.com/Nozbe/WatermelonDB/blob/e7df835c7ba58c950d0f09564e831d7f350ff987/src/Collection/index.js#L127) — we should push an array of all record changes (creates and updates) in that collection all at once.

Don't pay _too_ much attention to the implementation on the branch, since, as you can see, it's currently broken :) Records should first have their "warning flags" reset to "OK" status, and THEN notifications should be sent.

Let me know if this is helpful :)

**Comment by namjul** [comment]
Thank you. I will check this out this week.

**Comment by namjul** [comment]
My current status https://github.com/namjul/WatermelonDB/pull/1/files
This works now as intended. But i am not sure about the implementation.
I am iterating 2 times or all operations https://github.com/namjul/WatermelonDB/pull/1/files#diff-c5500afe3b4153f17b1903a7ac03029dR146
Maybe there is a better solution.

**Comment by radex** [comment]
@namjul can you submit a PR to this repo? It would be easier to review and give tips.

I think you can use `rambdax`'s `groupBy` (or something like that) to change a flat array of updated records into an array grouped by collection — taht would be one improvement.

The most important thing is to add/update tests for observation — i.e. set up a test where you batch create and update multiple records in multiple collections, and see that there was exactly one changeSet emitted per collection on `changes`… Check out Database/test, observation/*/test for inspiration… let me know if you need pointers for that

**Comment by radex** [comment]
@namjul Hey, did you have a chance to work on this a little?

**Comment by namjul** [comment]
@radex very sorry for the late response. Some personal struggles.
I created the PR https://github.com/Nozbe/WatermelonDB/pull/271
I updated the Database test for batching but possibly not fully covering. Also what test should i add if any? I commented about the `groupBy` solution you mentioned and that I was not able use it.
