### ISSUE TITLE
Observing Updates to Query

### ISSUE THREAD

**Issue by arosendorff** [Nozbe/WatermelonDB#218]
Hi there, is there a way to observe any updates to a query directly? I know that the documentation says that you would pass the items returned from the query to enhanced components that would then observe each item, but I would ideally like to be able to update my component when any item in the query changes, as I apply some sorting and filtering to the items.

**Comment by arosendorff** [comment]
@rkrajewski But will this update if any items in my query are changed? E.g. if one of my items' name changes, would the component refresh? I know there's `Query.observeWithColumns`, but I essentially want to be able to observe all columns of my model if possible.

**Comment by radex** [comment]
@arosendorff theres no built in support for this. It's generally best to do it on component level, since you can avoid a lot of re-renders this way. You can work around it by calling observeWithColumns with all the columns (you can set a constant somewhere with all of them), or by doing an rx composition (switchMap to a merge of all observes of individual items)

**Comment by arosendorff** [comment]
@radex Okay thank you. Yeah that's what I thought was the preferred way of doing things, I just asked because we have a list of objects that we filter to show specific ones, and the objects could be updated while the user is viewing the list. I think using the observeWithColumns will be the best way to solve it for now, thank you!

**Comment by radex** [comment]
@arosendorff I understand the filtering is too complex to do on database (query) level?
