### ISSUE TITLE
Render a collection with SectionList (React Native)

### ISSUE THREAD

**Issue by cwagner22** [Nozbe/WatermelonDB#228]
Let's say I have a collection of `blogs` which contain multiple `posts`. I want to render a list of the post titles, grouped by blog name (section). 

```js
const BlogPostList = ({ blogs }) => {
  const sections = blogs.map(blog => ({
    title: blog.name,
    data: blog.posts
  }));
  // sections should be in this format:
  // [
  //   { title: "Blog Name 1", data: [post1, post2] },
  //   { title: "Blog Name 2", data: [post3, post4] },
  //   { title: "Blog Name 3", data: [post5, post6] }
  // ]

  return (
    <SectionList
      renderItem={({ item, index, section }) => (
        <Text key={item.id}>{item.title}</Text>
      )}
      renderSectionHeader={({ section: { title } }) => (
        <Text style={{ fontWeight: "bold" }}>{title}</Text>
      )}
      sections={sections}
      keyExtractor={item => item.id}
    />
  );
};

const enhance = withObservables([], ({ database }) => ({
  blogs: database.collections.get("blogs").observe()
}));

const EnhancedBlogPostList = withDatabase(enhance(BlogPostList));
```
The issue is `blog.posts` will be a Query Object and not a collection because it hasn't been fetched yet, causing an error (`Tried to get frame for out of range index NaN`)
Would the correct way to do it be to call `fetch()` on each `blog.posts` and only render the `SectionList` once ready?

Otherwise, I tried to use the full `posts` collection instead. However, I can't group the `posts` by their blog name because I first need to fetch each post's blog.

**Comment by radex** [comment]
What you need to do is to fetch `blog.posts` — correct.

You can use another `withObservables` for that, subscribing to:

```js
posts: fromPromise(Promise.all(blogs.map(blog => blog.posts.fetch())))
```

you can also make it reactive (auto-update) by using an Rx composition of `posts.observe()` calls, instead of Promise.all.

Another possibility if you don't feel comfortable with Rx is to observe ALL posts alongside all blogs (instead  of fetching posts per blog), and then group posts together into blogs in JS. If you're rendering them all at once anyway, that's even better performance-wise, since you only fetch two queries instead of `1 + blogs.length` queries

**Comment by cwagner22** [comment]
Thank you for the help @radex. Observing all posts + all blogs and then grouping the posts by blog name works well.
