### ISSUE TITLE
CRUD and Components

### ISSUE THREAD

**Issue by carizzapanopio** [Nozbe/WatermelonDB#250]
I  feel like this is a dumb question. I am really new to working with react native and I want to use WatermelonDB. However, Im stuck. 

Where do it put this? 
`const postsCollection = database.collections.get('posts') `
I tried using that code inside the page that I am displaying, but I am getting the error **_database is not defined_**? 

Can you give me a sample code for that? Thank you and I would really appreciate your help.

**Comment by diegolmello** [comment]
You can `export` your database and `import` it where you want to use.

 [In the example](https://github.com/Nozbe/WatermelonDB/blob/master/examples/native/index.js#L18), they just create the database and pass it around via props. That's another way.

You could do this way:
```js
// database.js
const database = new Database({
  adapter,
  modelClasses: [Blog, Post, Comment],
})
export default database

// YourComponent.js
import database from '../database'
```

You're probably new to js too and that's ok.
Look around for import/export variables and functions and you'll be fine :)

Before I forget: Please don't cross post your questions as you did [here](https://github.com/Nozbe/WatermelonDB/issues/252#issuecomment-464182654).
It may disturb other people who are trying to fix their own issues.
Thanks.

**Comment by Stophface** [comment]
@diegolmello I have a similar problem: How do you preserve the database object across sessions, i.e. when you restart the app. Upon very first App start, I initialize the database like this

```
 const adapter = new SQLiteAdapter({
        schema: Foo,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            console.log(`[Database]: Error on bundled database: .... Error: `, error);
        }
    });

    const databaseObject = new Database({
        adapter,
        modelClasses: [
            Foo,
            Bar,
            Cat,
            SomeTable,
        ],
    });
```


Then, I can pass it down via the context API, something like

```
<DatabaseProvider
    database={databaseObject} />
        <App />
<DatabasePovider />
```

However, these lines `const databaseObject = new Database({...` I only call once, upon _very first_ App start, when the user opens the App for the very first time. I do not need to initialize the `databaseObject` every time again. If I would do that, then I would overwrite the content the App adds to the database... Thus, I am not having a database object, because `const databaseObject = new Database({...` is never called. Because of that, there is not `databaseObject` I can pass to the `<DatabaseProvider database={databaseObject} />`. 

But how can my app access the database then, when the App is restarted for example?
