### ISSUE TITLE
[SYNC / CUSTOM SYNC] Custom sync process with unchanged/synced status on create

### ISSUE THREAD

**Issue by nikopolidi** [Nozbe/WatermelonDB#253]
Hey guys I'm developing RN app and I'm trying to implement custom sync process. But it seems that when I create records fetched from API all WDB records has `syncStatus: "created"` and whole object under `changes` attribute.
Is it possible to have a way to have custom sync process that takes control of internal things syncStatus/changes etc?

I'm tracking this package since v0.9, I was looking forward for Sync docs, but it is seems it is not possible to use it as is with API services I'm using so I had to make something custom over WDB.

Please advice.

Thank you!

**Comment by radex** [comment]
> Is it possible to have a way to have custom sync process that takes control of internal things syncStatus/changes etc?

Not currently, but you can see that changes on _status and _changed are done in `sync/helpers.js`. So you're welcome to contribute a patch that allows those two helper functions to be replaced with your custom implementation

**Comment by radex** [comment]
@nikopolidi Hey, what's the status of the issue?

**Comment by nikopolidi** [comment]
@radex I have chosen another way of handling this because deadline is getting too close :-(
Unfortunately I have found weird bug-like behaviour which makes WDB working slow as hell. I'm going to create new issue with details

**Comment by radex** [comment]
> Unfortunately I have found weird bug-like behaviour which makes WDB working slow as hell. I'm going to create new issue with details

That's not good! Do make an issue!

**Comment by nikopolidi** [comment]
@radex I'm sorry for being silent that long but anyway...
I have figured a cause of slowness:
- I have app that syncs with remote data base on launch based on selected `project` after authorization.
- if user want to  change project database get's cleared with `db.unsafeResetDatabase()` and user navigated back to project selection to pull up remote db for selected project

Stack navigation looks like this
Login > Project Selection > Main stack navigation (tab navigation screens)
List screen content filled by `db.collection(collectionName).query().fetch()`
each item might have one property with 1-6 items loaded with using `withObserbables` frok another collection
What I have noticed: is even if screen has been unmounted and WDB observables has been used at any of Main stack screen lists the app goes slower each time reset>sync process happen.
It looks like there it is still observing items being destroyed by `unsafeResetDatabase`
Not sure if you could noticed that with small database, but I have 3 collections ~10 000 items each.
More `projects` you change slower app you get.
Here is some pseudocode cycle so you understand the flow
```
// login screen
login()
// loading screen
unsafeResetDatabase(); 
syncDatabase();
// main stack navigation
loadListWithObservables();
// back to login
logout()
```
After several times app goes really slow and hangs on screen

**Comment by radex** [comment]
> What I have noticed: is even if screen has been unmounted and WDB observables has been used at any of Main stack screen lists the app goes slower each time reset>sync process happen.
It looks like there it is still observing items being destroyed by unsafeResetDatabase

It's most likely, that your app is hanging onto some 🍉 objects, or isn't unsubscribing from some observed queries.... although it is possible there's a bug in 🍉 itself... 

You can try to use Chrome's memory debugger to see where the leak is

**Comment by nikopolidi** [comment]
Is there any way to force unsubscribe from watermelon object?

вт, 23 апр. 2019 г. в 16:40, Radek Pietruszewski <notifications@github.com>:

**Comment by crrobinson14** [comment]
Let me bounce a possible workaround off you. At a time when you need to do a full "on user logout" database clear, use a new database file entirely.

WatermelonDB allows you to specify `dbName` in its constructor, and if you don't specify one it defaults to `watermelon` per https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/sqlite/index.js#L101-L107. This becomes the file `watermelon.db` "on disk" on the device when the native side of the adapter gets ahold of it. You can override it thus:

```
const adapter = new SQLiteAdapter({
    schema,
    dbName: 'xyz',
});
```

What this means is you can also do this:

```
const dbName = await AsyncStorage.getItem('dbName') || myUuidOrShortIdFunction();
await AsyncStorage.setItem('dbName', dbName);
const adapter = new SQLiteAdapter({
    schema,
    dbName,
});
```

Now, if you want to clear your database, you can just delete that `dbName` AsyncStorage key. Per https://github.com/Nozbe/WatermelonDB/issues/251#issuecomment-464125982 WatermelonDB already allows the use of multiple databases so if you call your initialization code again, you get a fresh DB to work with.

We came up with this to address an on-logout performance issue, where it was taking 12 seconds to log out because per https://github.com/Nozbe/WatermelonDB/issues/384 bulk deletes can be slow (they're done one by one). Dropping the whole DB does an end-run around that issue.

But it occurs to me this may solve your use-case as well because the references to the old objects won't be invalidated until your components are fully destroyed as your UI reverts to the login screen. There might be some edge cases in complex nested observables but I think it might be worth a shot in your case seeing if straightforward cases "just work."

I don't see a "close database" method in the API but I would assume this would be a "nice thing to file a PR for, not a total blocker".

**Comment by radex** [comment]
> We came up with this to address an on-logout performance issue

@crrobinson14 why aren't you using `database.unsafeClearDatabase()` (or something similar - don't remember the exact name) ?

**Comment by crrobinson14** [comment]
For the same reason nikopoldi isn't. Inside a React Native app when you're deep into a logged-in UI it can be super hard to coordinate a "database clear, but wait until all those components and observers are totally unmounted and destroyed". The docs are pretty clear about this and you also get a ton of console warnings if you don't clean up all your observers. But React Native does this implicitly - you don't say "clean up observers," you have to destroy everything and hope it all happens.

If you just re-open to a new database you don't have any of these issues. The old items keep their old references until they're destroyed, but they can go in any order and it doesn't seem to hurt anything. The only thing I haven't sorted out is cleaning up the old DB file but that feels like an easy win.

**Comment by nikopolidi** [comment]
Correct, it is seems like you got that behavior. I have list with ~10k
records and I need to clear it on logout which is challenging because each
item have referenced document from another table which is loaded as
observable

вт, 25 июня 2019 г. в 21:08, Chad Robinson <notifications@github.com>:

**Comment by radex** [comment]
> For the same reason nikopoldi isn't. Inside a React Native app when you're deep into a logged-in UI it can be super hard to coordinate a "database clear, but wait until all those components and observers are totally unmounted and destroyed".

Hmm. What we do @Nozbe is we change topmost state of the entire view tree, to kill the whole component tree (and therefore observers get unmounted all at once), and then - now that the app is in "logged out" state, we can safely clear the database. I don't recall us having issues with that approach.

> The next line also says you must not have any pending actions, but WatermelonDB doesn't even currently expose a way to know this is happening. If you have an async code block running there is no way to know.

yeah, I made it safe against pending actions. It's best if you don't have them (because they might error out - so it's good to have error boundaries in component tree), but it shouldn't be unsafe.

It would be nice to do some underlying work in WatermelonDB to traverse the record caches to complete any observables, and same for query/record observables. (Pull requests appreciated -- I'm more than happy to give general pointers). But for now, the approach described above seems to work flawlessly. (Of course, your approach with switching to a new database name also works - but you have to delete the underlying database)
