### ISSUE TITLE
Can't find variable: Proxy

### ISSUE THREAD

**Issue by brian-perlego** [Nozbe/WatermelonDB#333]
Hello,

I have an issue using Android 9, it's not happening if I use the React Native Debugger. I don't know why but rambdax is using ES5.

Do you have any idea where it's coming from ?

Thanks
![Screenshot_1556105493](https://user-images.githubusercontent.com/47814339/56656392-4e348f00-668d-11e9-95f2-5e6fff360a5c.png)

**Comment by brian-perlego** [comment]
I downgraded rambdax to `1.5.6` and the issue seems to be fix.

Here is my environment btw:
"react": "16.6.1",
"react-native": "0.57.7",

**Comment by stigi** [comment]
@brian-perlego The problem is that React-Native on Android used to ship with an old JavaScriptCore library. One that doesn't support i.e. `Proxy` (amongst other JS features).

You've got different options:
- You can upgrade to React-Native 0.59+ which updates the JSC on Android
- Using https://github.com/react-native-community/jsc-android-buildscripts to bundle an updated JSC with your android project

**Comment by brian-perlego** [comment]
Thank you @stigi for the clarification!
