### ISSUE TITLE
Generate static html from markdown docs

### ISSUE THREAD

**Issue by shadeofgod** [Nozbe/WatermelonDB#372]
Hi,
So I only find there are raw markdown files when learning about this project, I've used mdbook to do such job since reading markdowns with lots of jumping around between different pages on Github is not a very pleasant experience.

you can check it here: https://shadeofgod.github.io/WatermelonDB-docs

Let me know what u think and I'm happy to send a pull request, maybe we can use github pages to host those static files and even set up in CI to automate it.

**Comment by radex** [comment]
This is awesome @shadeofgod !

I'd love to see a pull request for that. It would be neat if there was some sort of an automated / one command setup for this, so that I don't have to manually maintain this, but the docs just get automatically updated (or I only have to use a single cli command to regenerate docs)

**Comment by shadeofgod** [comment]
@radex sure this can be all done with travis ci,  I'm kinda busy recently doing my own job,  so bear with me it will take couple days to finish.
