### ISSUE TITLE
[Question] Sync remote backend database -- can it work with postgres?

### ISSUE THREAD

**Issue by simkimsia** [Nozbe/WatermelonDB#380]
I am more of a backend developer.

So under https://github.com/Nozbe/WatermelonDB/blob/master/docs/Advanced/Sync.md

I am unsure whether this sync is syncing directly with a remote database or with an API?

And are there any restrictions of the remote database type?

My thinking is that the remote database acts like a central final source of truth. 

The metaphor I am using to reason all this is Git and Github. Kinda like GitHub repo acts as the central source for the code. While local copies of the repo can make any changes they like, but when they want to sync with the GitHub repo (remote), they have to settle the conflicts locally before sending the changes to the remote GitHub repo.

Is that a suitable metaphor to reason abt sync?

**Comment by radex** [comment]
The metaphor is not perfect, because there's no branching or versioning, but yes, the backend database is supposed to be the source of truth.

WatermelonDB is local-only. It's bring-your-own-backend kind of thing. As long as the backend conforms to Watermelon Sync Protocol (it's just an informal spec, no implementation), it doesn't matter how you implement it. Internally, we use python and postgres.

**Comment by simkimsia** [comment]
Thanks for reply. I suppose when you say python and postgres, you mean the watermelonDB calls the API which is the python sitting in front of your postgres?

**Comment by kunaldodiya** [comment]
Will it work with Laravel Api ?

**Comment by KrisLau** [comment]
@krunaldodiya Late but for anyone else who might be looking for this, the docs has a document of [Existing backend implementations for WatermelonDB](https://nozbe.github.io/WatermelonDB/Advanced/Sync.html#existing-backend-implementations-for-watermelondb) which lists a Laravel implementation of sync
