### ISSUE TITLE
[DB] Uh-oh. Database failed to load, we're in big trouble TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by isllyend** [Nozbe/WatermelonDB#527]
"react-native": "^0.59.3",
"@nozbe/watermelondb": "^0.14.1",

what's up? Please help me ):

**Comment by chrise86** [comment]
I just faced this issue, what is the cause?

**Comment by scarlac** [comment]
@chrise86 This happens when your schema doesn't exist, for example you've imported your model/schema.js file incorrectly. Check your `import schema from '...'` statement and ensure that it's the default import if using this particular syntax, or use `import { schema } from '...'` if you are using a named export.
