### ISSUE TITLE
Optimistic Updates

### ISSUE THREAD

**Issue by natew** [Nozbe/WatermelonDB#543]
Just curious, does WatermelonDB support or plan to support optimistic updates (ie: mutations from the client side that immediately update on the client side)? Wanted to start a discussion as I didn't see any previous.

**Comment by radex** [comment]
> mutations from the client side that immediately update on the client side

I don't understand what you're suggesting

**Comment by crrobinson14** [comment]
I think he's talking about the GraphQL concept of "Optimistic Updates" aka Optimistic UI. https://medium.com/twostoryrobot/a-recipe-for-offline-support-in-react-apollo-571ad7e6f7f4

GraphQL was designed originally to streamline API calls. If you post a change, it needs to call the server. On a fast connection it is fine to wire this directly, but what happens if you are slow or offline while the call is waiting to time out? The screen does not update, so it looks broken. Optimistic UI writes the change locally first, assuming it will succeed, and then does the network call in the background.

@natew I think you can consider WatermelonDB as having this functionality by design. GraphQL is an API streamlining mechanism first, and you can add offline support as add-on behaviors e.g. via React Apollo and Optimistic UI. But WatermelonDB is a local/offline-first database FIRST, and then has some syncing as an add-on. You can review the documentation at https://nozbe.github.io/WatermelonDB/Advanced/Sync.html to see how this works. This was designed more for REST API calls but you could easily run Mutations and Queries to do the same job.

**Comment by radex** [comment]
Indeed!
