### ISSUE TITLE
WatermelonDB and Redux. Side by side

### ISSUE THREAD

**Issue by cvvspb** [Nozbe/WatermelonDB#598]
Greetings.

I've encountered problems with Redux with collections of tens of thousands of objects. The weakest part of Redux/AsyncStorage , I guess, is the RN bridge and state persistence. When the state grows to 10-20Mb of serialized JSON, the whole app starts to choke on each state change (Android platform shows the worst performance). I've tried different persistance modules, all the same.
So I'm looking for a replacement. The code base is quite big, and I've used redux-saga extensively.

Is it possible to use WatermelonDB with redux/redux-saga side by side without rewriting everything from the scratch?
Are there any pitfalls?

I'd like to migrate some parts of the app to the new framework gradually.

Thanks!

**Comment by cvvspb** [comment]
@district-michael Thanks for your answer, Michael!

**Comment by azizhk** [comment]
Just wanted to add here that `react-redux`'s `connect` creates a Pure Component.
https://react-redux.js.org/7.0/api/connect#pure-boolean

And as 🍉 's Models are mutating objects, you will need to take care to ensure that your components re-render.

**Comment by williamgurzoni** [comment]
> We are using both side by side at the moment, migrating the heavy data into WatermelonDB, while keeping the lite app state in redux without any issues.

Hello @district-michael I'm trying to do the same implementation. Are you using middleware to make Watermelon queries?

**Comment by williamdclt** [comment]
We're doing exactly that too: migrating large Redux slices to WMDB. It could be useful for other people so without going into much details, here's what we did:

- Have a "wmdb bridge" saga listening to the same actions as the reducer you're going to get rid of. It'll handle the writes into WMDB
- Sagas that need to read from WMDB can use `yield firstValueFrom(someObservable)` instead of `yield select(someSelector)` (firstValueFrom comes from the latest `rxjs`)
- Some of our selectors were using data that we're migrating to WMDB, and some other data that's staying in redux. These now return Observables, ie they had this signature: `(State) => ReturnType` and now have this signature `(State) => Observable<ReturnType>`
	- To make that work, we wrote a `connectObservable` HOC, which composes `connect` and `withObservable`

**Comment by sidferreira** [comment]
@williamdclt how do you access the database object in saga?

**Comment by williamdclt** [comment]
We moved away from WatermelonDB since then (we found it was too bleeding edge), so I don't remember all the details but IIRC you just import the database object that you created?

```ts
// somewhere in some sort of database.ts
export const database  = new Database(...)

// in your saga
import { database } from '../database'

function* mySaga() {
	yield database.write(...)
}
```

---

Correcting something I've written above while I'm at it, for future reference:
 
> Some of our selectors were using data that we're migrating to WMDB, and some other data that's staying in redux. These now return Observables, ie they had this signature: (State) => ReturnType and now have this signature (State) => Observable<ReturnType> 

We also came back from that, it was a horrible idea. It re-creates an Observable everytime the Redux state changes, which means re-connecting to the database and re-fetching the data. Instead, we made it the responsibility of the component/saga to fetch data from the DB and pass it to the selector. The selector looks like `(state: State, additionalDataComingFromTheDb: Something) => ReturnType`

**Comment by williamdclt** [comment]
My colleague did a talk which (amongst other things) goes over our trial of WatermelonDB and these connectObservable, if you're interested: https://www.youtube.com/watch?v=8FjGjXiTfyc&feature=youtu.be
