### ISSUE TITLE
Better debugging information for Diagnostic Errors

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#612]
We are dealing with a lot of `Diagnostic error: Cannot update a record with pending updates` errors these days. It's extremely hard to debug because it happens of course on somebody's client somewhere and is entirely dependant on their local state.

Would probably be easier to debug if table + ID was part of this error - maybe even properties. Something like `Diagnostic error: Cannot update a record with pending updates (table: documents, ID: 1234, pending_updates: title, body)`. Otherwise it's practically impossible to figure out *what caused the error*

What do you think? I could whip out a quick PR

**Comment by radex** [comment]
@esbenp Go for it! I'm a fan of helpful diagnostics :)

**Comment by esbenp** [comment]
Alright I will. I am not super familiar with everything but could you maybe elaborate on what is a common cause for this? Is it `preparedUpdate`s that are never flushed, or is it flushes that fail? Understanding what it means will help with making a better log statement

**Comment by radex** [comment]
this sets the pending update flag:

https://github.com/Nozbe/WatermelonDB/blob/c99f4a3c09354e33ab983b29c1d1be421ab48308/src/Model/index.js#L110

and this resets it:

https://github.com/Nozbe/WatermelonDB/blob/ee81f5ab6a95c5b930fddbe54a4a64bdcd103903/src/Database/index.js#L93

both happen synchronously when you correctly use this:

```
const record = record.prepareUpdate(x)
await database.batch(record)
```

so to hit this bug, you either have to prepare and update and then NOT pass it to batch synchronously (that's a bug, and watermelon in dev mode sends warnings about this), or something crashed on this path. example:

```
await database.batch(
  record1.prepareUpdate(),
  record2.prepareUpdate(x => { throw new Error() } )
)
```

record1 will be stuck with a pending update, because something else crashed before it got to the batch call

**Comment by esbenp** [comment]
This is super helpful information, thank you! I actually thought this was related to multiple clients editing/deleting the same thing and then crashing when syncing (this error appears when we sync in our app).

Searching for this error gave me nothing, but I am thinking this would be extremely helpful as a "Common errors" in docs - what do you say?

**Comment by radex** [comment]
@esbenp yeah! that would be very helpful! `docs-master` is where you can put in .md format documentation

**Comment by bureyburey** [comment]
joining in on the issue.

using these versions:
@nozbe/watermelondb: 0.21.0
@nozbe/with-observables: 1.2.0

we've also been encountering this same problem with several of our users.
we do not use **prepareUpdate** or **database.batch()** in our app, so I assume it comes from within 🍉  itself.

has there been any changes in the library that may cause this since this ticket was closed?

what's even more troubling is that we were unable to reproduce it by ourselves...
would love to hear your input on this :)

**Comment by davevilela** [comment]
@bureyburey I'm also having this problem, and it doesn't seem to have anything related to using prepareUpdate, as I haven't found a single usage of this method in my entire codebase.

**Comment by rohankm** [comment]
im getting this error on delte
`Diagnostic error: Cannot mark a record with pending changes as deleted`

**Comment by sarthakpranesh** [comment]
I have a common database wrapper were I have applied a really simple fix for this. All I did is wrap my `r.prepareUpdate` in a try-catch block, if it throws an error I log the error as warning and return the same record back (without calling prepareUpdate) so the developers consuming the DB wrapper know that they had possibly supplied two records that are same for batch update or their was a already existing prepared update for the record that did not get batched.

This does the trick for me for now.
