### ISSUE TITLE
Firt sync

### ISSUE THREAD

**Issue by SavioScaglioni** [Nozbe/WatermelonDB#700]
I'm having trouble with the first sync. I use the prepareCreate function, but the line status is not 'synced', even if I assign it to the object. Can someone help me?

Code example:
`db.collections.get('empresa').prepareCreate((empresa) => {
    empresa._raw.id = objEmpresa.id;
    empresa._raw._status = 'synced';
    empresa._raw._changed = '';
    empresa.nome = objEmpresa.nome;
    empresa.cnpj_cpf = objEmpresa.cnpj_cpf;
    empresa.cod_empresa = objEmpresa.cod_empresa;
    empresa._raw.created_at = objEmpresa.created_at;
    empresa._raw.updated_at = objEmpresa.updated_at;
  });`

Result:

id:3
_status:updated
_changed:nome,cnpj_cpf,cod_empresa
nome:TESTES 123
cnpj_cpf:XXXXXXXXXXXXX
cod_empresa:0003
created_at:2020-04-25 01:44:00
updated_at:2020-04-25 01:44:00

**Comment by radex** [comment]
why are you modifying _raw ? what are you trying to achieve, exactly?

**Comment by SavioScaglioni** [comment]
This information is coming from the backend, so I don't need to sync. I need to insert it in the local bank (Watermelondb) and make this information have the status 'synced', so that they are not synchronized.

**Comment by radex** [comment]
@SavioScaglioni makes sense. your code should work, though would be easier to use `Collection. prepareCreateFromDirtyRaw({ put your JSON here })`. I suspect you may be updating this record somewhere after all. send a bigger snippet of code

**Comment by martinodonnell** [comment]
@radex I am trying to work out sync too. I have set up the sync functionality correctly. (Seems right) When you call sync when the app first loads, all the records in my backend get added with watermelons ID. I have uuids associated with them already. Is there anyway to use these instead of the watermelons ID?

Also should you use synchronise to initially load in all the data? Any changes made in the backend will come in as updates rather than changes so will give out an error when returned from the pull function in synchronise. Should you instead just call the pull api and add the data in yourself? Is this way ```prepareCreateFromDirtyRaw``` is for? 
Thanks

**Comment by barbalex** [comment]
`prepareCreateFromDirtyRaw` is very handy. Seems to me it is not documented or have I missed it?

**Comment by radex** [comment]
@barbalex You're not wrong. A quick PR with an update to docs-master/ (you can do that via browser) would be appreciated!

**Comment by barbalex** [comment]
@radex  done: https://github.com/Nozbe/WatermelonDB/pull/866
