### ISSUE TITLE
Support for eagerly joined relationships

### ISSUE THREAD

**Issue by pokey** [Nozbe/WatermelonDB#763]
Have you considered adding support for relationships that are joined eagerly?  Syntax could be something like:

```js
export default class Foo extends Model {
  static table = 'foos';
  static associations = {
    bars: {type: 'belongs_to', key: 'bar_id'},
  };

  @eagerRelation('bars', 'bar_id') bar;
}
```

Then this could just be used as `foo.bar` rather than `await foo.bar`.  Would make some code much cleaner and easier to debug by avoiding all the `await`s littered everywhere.  See SQLAlchemy's [joined loading](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html) for a reference.

**Comment by radex** [comment]
@pokey This would be nice, but quite tricky to implement as long as watermelon's API is asynchronous at all. Look:

case 1: you `db.get('foo').find('x')`. we can add some logic to fetch all eager relations to guarantee the ability to access x.bar synchronously.

case 2: `x.bar.id = 'blah'`. ok, so now, the Model.update() and Database.batch() have to find the `blah` Bar so that after asynchronous update, x.bar is still available, spreading knowledge about model's relations to all sorts of unrelated places. I think doable, though ugly, and I do worry about performance in some cases, when you batch update records.
