### ISSUE TITLE
Syncing many-to-many relations

### ISSUE THREAD

**Issue by pokey** [Nozbe/WatermelonDB#771]
If I have a table to represent a many-to-many relation, how are conflicts handled?  Ie what if I add a relation between 2 entities, and someone else adds the same relation?  What if I delete when someone else tries to create (presuming they don't yet have the prev create)?

On a related note, there do not appear to be any uniqueness / primary key constraints for these many-to-many relationships, so I think I can guess the answer to the above questions, but wanted to know if this is something that had been considered, as I don't see it mentioned in the docs

**Comment by radex** [comment]
> Ie what if I add a relation between 2 entities, and someone else adds the same relation? What if I delete when someone else tries to create (presuming they don't yet have the prev create)?

Hi, there's no built-in mechanism for this. The approach we took at Nozbe is to embed these constraints on the sync server, not client, since a client can always lie.

If you want to implement this on the frontend, you can do it in your app's code, or you can add an hook to synchronize() that allows you to do processing on pulled data before it's committed to the local database.
