### ISSUE TITLE
batch prepareCreate for many-to-many

### ISSUE THREAD

**Issue by educkf** [Nozbe/WatermelonDB#802]
Hello there!

Sorry for the newbie question, I started testing with WatermelonDB yesterday, and I am not totally used with database concepts.

My question is: when I will batch create a lot of `Products`, for example, and each product have many `Tags` (which, I understand, needs a relational table to deal with `ProductsTags`), can I do everything at once on `prepareCreate` ?

I could not find it on the docs, maybe I can help adding to it at the end, in case it does not exists yet.
My code for batch create is currently like this (inspired by another issue found here):

```
await database.batch(
      ...toCreate.map((productData) =>
        database.collections.get('products').prepareCreate((product) => {
          
          // force an id, to match with remote database id
          product._raw.id = productData.id_erp.toString();

          // add each entry product to its respective column
          for (const [key, value] of Object.entries(productData)) {
            product[key] = value;
          }

          // maybe here I can make the link between products and tags? 
          // They come as an array of tags ids, like this: tags: ['23', '35', 55']
          // and tags are saved on DB with those same ids
        }),
      ),
    );
```

Thanks in advance!

**Comment by radex** [comment]
Hi, there you go: https://nozbe.github.io/WatermelonDB/Relation.html#many-to-many-relation

**Comment by educkf** [comment]
Hi, @radex , thanks for the link!

I have been there before, and it was not explicit to me how to handle the case I posted. Actually, it is still not clear... I mean, on the link I see the models part, how to query, and other stuff, but it is quite not evident how to create and add new content so it makes the link. I can contribute to that, to extend and improve the explanation for that. If you can just give me a highlight of how should I start, than maybe I can investigate further.

Thanks!

**Comment by jrounsav** [comment]
Hey @educkf  
We have a similar use-case except my app has a list of Contacts & Tags instead of Products, and our tag names are included in objects with the IDs. You should be able to achieve the outcome for your own app in a similar fashion.

Ie. our incoming contact looks like this
```
Contact {
    contactId: number;
    name: string;
    tags: [
        ...,
        {
            tagId: number;
            tagName: string; 
        },
        ...
    ]
}
```

I'm accomplishing the batch in 3 steps:

1. Iterate the contacts to prepare create/update & generate a list of tags to be created from the contacts. While this is happening I am also creating a map of contacts => tags, as well as a map of contact remote IDs => watermelon IDs (which you receive from prepareCreate and Update)
2. Iterate the new list of tags to prepare create/update & again generate a list of tag remote IDs => melon IDs
3. Iterate the map of contacts => tags to plug into the many-to-many pivot table. Because you received the map of local IDs to remote IDs when building the prepareCreate/Update batches in steps 1&2 you can now build out the pivot table using the local melon IDs. This means you can use the lazy decorator as described in the docs.

Since you're only getting the remote IDs with your products you probably won't need to do as much work around updating tags as I did, so it may be a bit easier. Hope this helps!
