### ISSUE TITLE
How to test experimental JSI on Android?

### ISSUE THREAD

**Issue by diegolmello** [Nozbe/WatermelonDB#814]
On [Set up database](https://nozbe.github.io/WatermelonDB/Installation.html?highlight=jsi#set-up-database), there's this option:
> // experimentalUseJSI: true, // experimental JSI mode, use only if you're brave

I'm brave (at least, my mom says I am), but I don't know how to set it up...

And how can I tell it's working through JSI? Is there a log?

**Comment by radex** [comment]
JSI doesn't quite work yet on Android… It does work in the tester project: https://github.com/Nozbe/WatermelonDB/tree/master/native/androidTest -- you can look at history in this folder to see how to set up grade to compile JSI... but you'll probably found that it crashes your app, and you will have to use patch-package to change CMakeLists to fix up relative paths from your project to WatermelonDB node_modules... I'd like to get it working sometime in the next month or two in Nozbe Teams, so hopefully you should see progress soon :) 

On iOS, I don't recall there being any special handling required. I might be forgetting something, but I think it's as easy as switching the flag to true, since all the C++ code is already compiled with the app.

> And how can I tell it's working through JSI? Is there a log?

If you enable JSI but it doesn't actually work, it will make a console log that it's falling back to asynchronous adapter

**Comment by diegolmello** [comment]
Got it.
I'm closing, but one more question: with JSI fully working, will we still need async/await for all operations?

Thanks.

**Comment by radex** [comment]
@diegolmello Yes. We can add a separate set of `xxxSync` APIs, but I want the flexibility to do things asynchronously (for many reasons, but for example to be able to run things concurrently when we don't need an immediate response; once React Suspense is fully production-ready then that might also be a good idea performance-wise… and to be able to support different platforms which may never be able to be synchronous)

**Comment by diegolmello** [comment]
Ok, thanks.
