### ISSUE TITLE
Strategy with different browser's tabs used at the same time?

### ISSUE THREAD

**Issue by frederikhors** [Nozbe/WatermelonDB#827]
Is there a strategy for when different tabs are used in the browser at the same time?

RxDB uses [Leader election](https://rxdb.info/leader-election.html).

**Comment by radex** [comment]
Alas, there is not, and doing this right is very complicated and Hard™. For my use case, I'm assuming that there is eventual consistency because every tab is a full-fledged app that synchronizes with a remote server.

There is however a known issue with data corruption with `incrementalIDB` option on LokiJSAdapter under some unusual circumstances, which I'll be fixing in coming weeks, but generally, it works fine.

**Comment by awgv** [comment]
@frederikhors

Not sure how helpful it’ll be a month from being asked, but RxDB uses [pubkey/broadcast-channel](https://github.com/pubkey/broadcast-channel) to do that; I understand that it’s not an out-of-the-box solution, but it’s something.

**Comment by radex** [comment]
WatermelonDB v0.21.0 fixes the issue with possible data corruption when multiple browser tabs are open. However, the assumption is that an application relies on online sync to keep tabs synchronized. There's a new LokiJS extraIncrementalIDBOptions.onDidOverwrite handler that's called when IDB needs to be overwritten. This can be used, if user is offline, to alert the user not to close the tab, lest changes will be lost

**Comment by castroCrea** [comment]
Hello, @radex do you have an example of implementation? Do the observers work?

**Comment by radex** [comment]
@castroCrea Like I said above, there isn't a reliable way to get this done. (RxDB's approach only kind of works, but is fundamentally flawed and leader election cannot be made reliable on the web currently). The best I can recommend right now is to rely on sync, and add extraIncrementalIDBOptions.onDidOverwrite to warn multi-tab users that they must not close the tab with changes until they go back online.
