### ISSUE TITLE
Qn: In memory database for react-native

### ISSUE THREAD

**Issue by bsr203** [Nozbe/WatermelonDB#83]
Hi,

I tried to use `lokijs` to run my test / storybook with sample data. Do you see issues using this adapter on react-native env. I currently get 
```
error: bundling failed: Error: Unable to resolve module `fs` from `/Users/bsr/myApp/node_modules/lokijs/src/lokijs.js`: Module `fs` does not exist in the Haste module map
```

**Comment by radex** [comment]
You'd probably need to mock `fs` so that there's no bundler error, and also tweak the adapter initializer code so that you can use an in-memory database.

But you could also tweak the SQLite adapter to allow in-memory databases. That would be easier.

Both already work, but only in test environment. It wouldn't be difficult to change. I can give you pointers if you can send a pull request adding this capability.

**Comment by bsr203** [comment]
sure. may be sqlite inMemory mode is better as we don't need other drivers and dependencies. I think it will be useful for testing in isolation. thanks

**Comment by radex** [comment]
Well, I assume you're already using the React native native module for SQLite, so there's no extra dependencies.

Loki should work too. We use that in common tests (but that runs in Node)

**Comment by bsr203** [comment]
so is there an easy way to configure the adapter to pass through [:memory](https://www.sqlite.org/inmemorydb.html) config

**Comment by radex** [comment]
I already said:

> Both already work, but only in test environment. It wouldn't be difficult to change. I can give you pointers if you can send a pull request adding this capability.

**Comment by bsr203** [comment]
:-) I was asking about the pointers you said. quickly searched through the codebase and didn't find the driver setting. Sorry, didn't look through all the code yet.

**Comment by radex** [comment]
@bsr203 You'll have to start from this branch, not master, as there were changes in this area:

https://github.com/Nozbe/WatermelonDB/pull/70/files#diff-010253597e9bd62ff04e3105667f6b66R45

right now, the database name is passed directly to sqlite only in test mode, otherwise documents filesystem path is prepended.

This can be changed so that if dbName is `:memory:` or contains `mode=memory`, it's passed directly without prepending FS path.

I think this should work on Android without any changes. But if no, this is the line:

https://github.com/Nozbe/WatermelonDB/pull/70/files#diff-2050916f6706022d034a09ab20dd9ed4R14

You'll find instructions for Xcode / Android setup and running native tests in CONTRIBUTING.md file

**Comment by bsr203** [comment]
@radex thanks for the details. I probably can't get to it right away, and let you know. thanks.

**Comment by radex** [comment]
Closing this. @bsr203 feel free to ask Qs if you want to get to implementing this in the future
