### ISSUE TITLE
Upsert - Is this/will this be supported?

### ISSUE THREAD

**Issue by jspizziri** [Nozbe/WatermelonDB#837]
1. Is upsert supported somewhere and I just can't find it?
2. If it's not supported, will it be?
3. If it will be what's required to implement it?

Thanks!

**Comment by radex** [comment]
> Is upsert supported somewhere and I just can't find it?

No.

> If it's not supported, will it be?

Maybe! How exactly do you envision the API?

**Comment by lucas2595** [comment]
Wouldn't something like the code below work (despite not being optimal performance-wise)?

```JS
const newRow = {...}

await database.action(async (action) => {
  const collection = database.get('model_name')
  const localData = await collection.query().fetch();
  let localRecord = localData.find(
    row =>
      row.id === newRow.id &&
      !row._hasPendingDelete &&
      row.syncStatus !== "deleted"
  )

  if(localRecord) {
    await localRecord.update(newRow)
  } else{
    await collection.create(newRow)
  }
})
```

**Comment by jspizziri** [comment]
@lucas2595 yes, this is totally possible (that's currently how I'm doing it). Upsert is primarily useful from a performance and code simplicity standpoint.

**Comment by jspizziri** [comment]
@radex 

Sorry, it took a while to get back to you. Here are my initial thoughts; very much interested in your improvement upon/complete scrapping of them 😄 . All based on the [language ref here](https://www.sqlite.org/lang_UPSERT.html).

----

### `SELECT` Statements In Upsert
I think allowing `SELECT` statements in the upsert gets overly complicated and so this functionality should be left out. Perhaps if this needs to be solved it could be supported by/required to drop into writing raw SQL statements.

### `ON CONFLICT`'s

My initial thought is simply to allow the user to pass in an array of `string`'s. Those strings representing **indexed** properties on the model. The existence of those properties and their indexing presumably would be determined by the metadata stored on the model and in the schema. (I believe there's another issue for this somewhere but it would be cool to expand the field decorator to allow for various schema metadata such as the `type` of the column in the DB and if it's `indexed` or not. In that scenario, you could effectively generate your schema file entirely from your models. But i digress.)

### `SET` Statements
I think the default set behavior could always be something like for every property
on the model:

```
SET prop = excluded.prop
```

Having more complicated `SET` statements is where it gets interesting, and I don't have a great idea for this other than allowing the user to specify a hash of keys and values representing their own `SET` statements at their own risk, à la:

```js
// prop1 = prop1 + 1, prop2 = prop2 || ", " || excluded.prop2
{
  'prop1': 'prop1 + 1',
  'prop2': 'prop2 || ", " || excluded.prop2',
}
```

The idea of allowing raw SQL to be specified always makes my skin crawl, but I don't see a way of simply getting around this another way. And if users could ultimately use a raw SQL statement on their own, it's sort of always a "caveat emptor" situation.

### Interface?

So effectively with those two things in mind, I arrived at the following interface. Please note, it's entirely possible that these are terrible ideas 😱 .

```ts
class Collection<Record extends Model> {
  public upsert(
    recordBuilder?: (record: Record) => void,
    
    // conflicts being an array of indexed property ids
    // with the default simply being "id".
    conflicts?: string[] = ['id'],

    // setters being a hash of properties to set, and how to set them
    // with the default simply being empty, as the assumed default
    // functionality is to simply overwrite all properties with 
    // 'prop = excluded.prop'.
    setters?: { [key: string]: string } = {},
  ): Promise<Record> {
    // ...
  }

  public prepareUpsert(
    recordBuilder?: (record: Record) => void,
    
    // conflicts being an array of indexed property ids
    // with the default simply being "id".
    conflicts?: string[] = ['id'],

    // setters being a hash of properties to set, and how to set them
    // with the default simply being empty, as the assumed default
    // functionality is to simply overwrite all properties with 
    // 'prop = excluded.prop'.
    setters?: { [key: string]: string } = {},
  ): Promise<Record> {
    // ...
  }
}
```

Thoughts?

**Comment by radex** [comment]
> Thoughts?

Simply doing an upsert on SQL level is completely doable in a few ways, but on the JS/reactive layer, it's tricky.

`recordBuilder?: (record: Record) => void,`

I'm not sure this can work (in a way that would be a perf improvement over what you can do already). `Record` would have to be either a new record (but if and only if none exists in DB - so we have to check it), or an existing record (if it exists). In theory, one could make a dummy record just to have access to the JS model class, but then only take its ._raw for the UPSERT. This breaks WatermelonDB's assumptions though - there's a general principle that a record in DB (unique by its ID) is always represented by one and only one JS object. Is it worth to break that principle and complicate the programming model? I'm not sure.

It's much easier to justify UPSERT that's only based on setting raw values, but the DX is not so good.

> prepareUpsert(

I'm not sure a prepareUpsert can work, because again, there's an assumption that if `prepareX` returns you an object, this object will maintain its identity after saving. But you can't guarantee that if a record with the given ID already exists...
