### ISSUE TITLE
[React-Native] Diagnostic error: Collection.create() can only be called from inside of an Action

### ISSUE THREAD

**Issue by iMokhles** [Nozbe/WatermelonDB#846]
i faced this issue even if it's called inside subAction or an action
`Diagnostic error: Collection.create() can only be called from inside of an Action`
codes cause the issue

1st function ( have the same for different Model and schema )
![Capture d’écran 2020-10-24 à 06 31 32](https://user-images.githubusercontent.com/1247248/97067884-c94c6d80-15c2-11eb-8669-ce72c73d512f.png)

2nd function ( have the same for different Model and schema )
![Capture d’écran 2020-10-24 à 06 31 55](https://user-images.githubusercontent.com/1247248/97067896-dcf7d400-15c2-11eb-9407-5e3ca011e662.png)

my app has 2 screens each one of them is a function component 

i use `React.useEffect( ... )` inside both of them to show a loading hud while downloading and saving my data from server to WatermelonDB

1st screen HomeScreen ( code works fin and save my data correctly )
![Capture d’écran 2020-10-24 à 06 36 47](https://user-images.githubusercontent.com/1247248/97067959-5d1e3980-15c3-11eb-9995-27dbf7495751.png)

the issue appears after 1st screen's code is done, after calling 
```
setCategories(categoriesObjects)
setLoading(false)
```
i go to the second screen with similar code the issue appear

2nd screen MoviesCategoriesScreen
![Capture d’écran 2020-10-24 à 06 41 08](https://user-images.githubusercontent.com/1247248/97068008-e7669d80-15c3-11eb-82b0-0d58462994fb.png)

if i go to 2nd screen `MoviesCategoriesScreen` directly the issue appear ( but if i refresh the app go to `MoviesCategoriesScreen` the code will work correctly and the database will be created without any issue )

i tried to check if the code running in action by using the same condtion used inside _ensureInAction function but no luck first execute cause the problem second no.

Any help or advice ?

**Comment by iMokhles** [comment]
@radex any update ?!?!

**Comment by radex** [comment]
@iMokhles Sorry, but there isn't too much I can do by looking at snippets of code if the issue is not immediately obvious. Debug the code yourself:

https://github.com/Nozbe/WatermelonDB/blob/master/src/Database/index.js#L258 - this is the invariant 
https://github.com/Nozbe/WatermelonDB/blob/master/src/Database/ActionQueue.js - and this is the queueing logic

sprinkle it with `debugger` commands and step through the code until you find the issue. Most likely, it's an issue that's going to seem obvious in retrospect… Or there's a small chance that you found a legitimate WatermelonDB bug, but then I'd need repro steps to do something about it
