### ISSUE TITLE
TypeError: null is not an object (evaluating 'DatabaseBridge[methodName]')

### ISSUE THREAD

**Issue by VanishedPlanet** [Nozbe/WatermelonDB#853]
i keep getting this error whenever i use watermelon db

**Comment by stylder** [comment]
I have the same issue

**Comment by leo-tavares** [comment]
This problem is similar to #844 . This error message means that lib has not been configured correctly.

Are you using react-native? If it is, keep in mind that the link must be MANUAL

I have faced this problem in the past and it has been resolved with the manual link
Questions: 
- What is your environment?(web/mobile)
- What version of lib?
