### ISSUE TITLE
Multiple syncing options

### ISSUE THREAD

**Issue by lms11** [Nozbe/WatermelonDB#875]
Hello there! This is a soft of feature request, so not sure if this is the proper place to ask.

I'm trying WatermelonDB for my project and I have a situation where 2 tables could change a lot in different times. I'd love to trigger a sync in two moments
- After cold start
- When user requests a sync for them

For (1), the existing solution is fine. For (2), I'd love to be able to sync only one table at a time. That is, have separate "last pulled at" and be able to handle them separate. Also, with that, doing pagination would become much easier (today's it is possible, but slightly trickier).

Thanks!

**Comment by radex** [comment]
> For (1), the existing solution is fine. For (2), I'd love to be able to sync only one table at a time. That is, have separate "last pulled at" and be able to handle them separate

why though?

**Comment by lms11** [comment]
Our main reason is separating hot and cold data: stuff we need to load more urgently vs. stuff I can load in background and don't need to block user's usage. Having to load them all together adds up in terms of speed.

**Comment by radex** [comment]
> Having to load them all together adds up in terms of speed.

Is this your assumption, or have you tested this to be true? Incremental syncs tend to be very fast in WatermelonDB (well, if your backend responds promptly), unless they're very, very big.

> I'd love to be able to sync only one table at a time

There's no support for this and I strongly recommend against doing this, as unless you've thought very deep and hard about the problem of synchronization, you might be not appreciating the difficulty of performing sync correctly. However, if you insist on doing this, I suggest that you make a PR adding to the `synchronize()` method two new options: `collections: TableName<any>[]` (which collections to sync), and `localStoragePrefix: string` (prefix for sync-related settings -- like last synced at -- so that you can have more than one)
