### ISSUE TITLE
Json field not populated during Sync pull

### ISSUE THREAD

**Issue by martinodonnell** [Nozbe/WatermelonDB#886]
I have been using sync to populate my database and have need for an advanced field which holds json  I have created the column as per the docs and can successfully create and update the media column with the object `{"one": "up", "three": "down", "two": "down"}`. My problem arises when I try to populate the field using the sync functionality. When I call sync pull using the changes below and query the result, the organisation is returned but media comes back `null`. Any ideas why?

Pull Changes
```
{
   "created":[
      {
         "id":"1",
         "organisation_name":"Your Restaurant",
         "uuid":"92884c27-d025-4c61-a958-86dbaa8b072d",
         "organisation_is_active":1,
         "created_at":1587672716,
         "updated_at":1604060827,
         "time_offset":0,
         "temp_scale":0,
         "media": {"one": "up", "three": "down", "two": "down"}
      }
   ],
   "updated":[
      
   ],
   "deleted":[
      
   ]
}
```

Model
```
const mediaSanitizer = input => {
  return input;
};

export default class Organisation extends Model {
  static table = 'organisations';

  @field('organisation_name') organisation_name;
  @field('uuid') uuid;
  @field('organisation_is_active') organisation_is_active;
  @field('created_at') created_at;
  @field('updated_at') updated_at;
  @field('time_offset') time_offset;
  @field('temp_scale') temp_scale;
  @json('media', mediaSanitizer) media;
}
```

Schema
```
tableSchema({
  name: 'organisations',
  columns: [
    {name: 'organisation_name', type: 'string'},
    {name: 'uuid', type: 'string'},
    {name: 'organisation_is_active', type: 'number'},
    {name: 'created_at', type: 'number'},
    {name: 'updated_at', type: 'number'},
    {name: 'time_offset', type: 'number'},
    {name: 'temp_scale', type: 'number'},
    {name: 'media', type: 'string', isOptional: true},
  ],
}),
```

**Comment by radex** [comment]
> Any ideas why?

yes.

> {name: 'media', type: 'string', isOptional: true},

note `string`.

**Comment by martinodonnell** [comment]
@radex The [docs ](https://nozbe.github.io/WatermelonDB/Advanced/AdvancedFields.html) say to put it in the schema as a string

![image](https://user-images.githubusercontent.com/22416103/101538692-6574dd00-3995-11eb-8611-b103f5e135d0.png)

**Comment by WJimmyCook** [comment]
I'm running into the same issue, did you ever figure it out @martinodonnell ?

**Comment by martinodonnell** [comment]
@WJimmyCook No.I would love if it did

**Comment by WJimmyCook** [comment]
Looks likes my issue is because the server API is returning an array instead of a string.

Look at the function _setRaw function, if the column type is a string then the value has to be a string otherwise it's set to null or an empty string.
https://github.com/Nozbe/WatermelonDB/blob/master/src/RawRecord/index.js

If I stringify the array then the sync works as expected.

**Comment by martinodonnell** [comment]
When you pull it into your component, I assume you have to parse it into a Json array then?

**Comment by ChrisSimoniMBT** [comment]
> Any update on it? When I use queries to create a row, it is getting populated correctly but not working with sync pull.

You have to stringify all json fields before sending them to WatermelonDB to be synced. WatermelonDB does not stringify them for you. A good upstream solution would be to maybe add a schema type of json that is string behind the scenes with a JSON.stringify on the object first. A good solution otherwise is to iterate over your records server side and stringify all json fields ahead of time.
