### ISSUE TITLE
[QUESTION] Edge cases of sendCreatedAsUpdated and more details of Current sync limitations

### ISSUE THREAD

**Issue by rutsatz** [Nozbe/WatermelonDB#913]
What are the edge cases described in:

> sendCreatedAsUpdated: boolean - if your backend can't differentiate between created and updated records, set this to true to supress warnings. Sync will still work well, however error reporting, and some edge cases will not be handled as well.

Could someone provide more details on how to implement the details provided at:

> During next sync pull, changes we've just pushed will be pulled again, which is unnecessary. It would be better if server, during push, also pulled local changes since lastPulledAt and responded with NEW timestamp to be treated as lastPulledAt.

thank you so much!

**Comment by radex** [comment]
> What are the edge cases described

I don't remember off top of my head.

Somewhere below this line: https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/test.js#L448 is the answer. I think this might have to do with what happens if a record is deleted and then we receive it in pull

**Comment by olliewd** [comment]
> What are the edge cases described in:

FWIW, I also wanted to understand this more, and I found this information very helpful: https://nozbe.github.io/WatermelonDB/Implementation/SyncImpl.html#sync-procedure

As radex says, there is a difference in how locally deleted documents are treated after a pull: 

When we locally mark a record as deleted, but then we receive an update for that record on a pull, the update will be ignored, and the record will be signalled for deletion on the subsequent push (i.e. client wins). Therefore, presumably, when sendCreatedAsUpdated is true, we'll always ignore the server updates for records that are locally marked as deleted.

However, a different behaviour happens when records locally marked as deleted are told to be created on a pull. In this case, we'll locally un-delete the record, and we'll update that record with the values from the created record (i.e. server wins).

Hopefully, this is the only different as far as edge cases are concerned. Actually, in my particular setup, the behaviour with sendCreatedAsUpdated: true is more convenient.
