### ISSUE TITLE
how to use " database " instance 

### ISSUE THREAD

**Issue by luksrocha** [Nozbe/WatermelonDB#928]
The documentation just say after we create the " database " instance at index.js, to use collections, and we just need to use "database.collection.get('model'), but when I try it, the console show me that : "Can't find variable: database".

I need to export or import " database " ?

**Comment by avinashlng1080** [comment]
Yes.  Look at how they are doing it on RocketChat.


You have to create the database instance and then reference it wherever you need it.

**Comment by luksrocha** [comment]
Can I do it at index.js on root (there is any problem in not instance it here) ? Or I can create the database instance somewhere else and just reference it whenever I want ?

**Comment by avinashlng1080** [comment]
It does not matter where you define it for as long as you are referencing it.

Just give it a go and you will be fixed :)

**Comment by Stophface** [comment]
@luksrocha  I have a smiliar problem. I initialize the database object once (!), upon first app start with a bundled database.

    const adapter = new SQLiteAdapter({
        schema: whatever,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            ...
        }
    });

    const database = new Database({
        adapter,
        modelClasses: [
            Country,
            ...
        ],
    });

Now I have a database object called database because of const `database = new Database(..... `
This database object I can use to access the database, which works fine. 

```
<DatabaseProvider database={database}> 
    <App/> 
</DatabaseProvider>
```

However, imagine I open and close the App. Then I basically loose the database object because I am not initializing the database again, because it happened already. By doing it again, I would overwrite my already initialized database. Thus, there is no `const database = new Database(... `executed. 

How would I access the database now?!
