### ISSUE TITLE
Schema creating columns without types

### ISSUE THREAD

**Issue by sandeep-eroad** [Nozbe/WatermelonDB#936]
The table created has columns of type `unknown`. 

![image](https://user-images.githubusercontent.com/48039040/106980103-75a60e80-67c4-11eb-9431-8b36c8d60044.png)

Is there something I have missed?

**Comment by sandeep-eroad** [comment]
I'll use this ticket to report an issue with migrations. I added a table and then added some columns using migration, but when I try to assign a value to the new column I get an exception. Do I need to do something extra to prevent this error?

**Comment by radex** [comment]
> The table created has columns of type unknown.

expected, sqlite does not have the concept of a columnn type

**Comment by scarlac** [comment]
Future commenter here. Let me share my mental notes for any potential readers:

I looked into this and it's no longer true that it doesn't have a concept of column types. In fact, it has been so for a while, but it has a few concepts for it that readers should know about. Mainly what OP would be seeing would be something they call "affinity" meaning what a column is more likely to be of more than a rule. In a normal server-based RDBMS it would be enforced, but in SQLite you can say a column is 'integer' and then proceed to insert 'banana' into it. In fact, it's even looser than that: You can define a column of the _type_ 'banana':
<img width="357" alt="image" src="https://user-images.githubusercontent.com/895369/205113408-da450f62-8034-4e20-9efc-f5d06b1a4b1f.png">

This begs the question: What the hell happens when it's `banana`? This is all documented in the docs, so I won't go into details:
https://www.sqlite.org/datatype3.html

In my opinion, Watermelon would have benefitted from defining a column type, even if it isn't strict. It helps inform debugging UIs on how to present and insert data and lowers the chance you make a mistake. For example, an inexperienced engineer may insert a string into a numeric column and then see the wrong ordering. This leads to wasted engineering time.

Anyway, SQLite "recently" a "strict" mode that allows the type safety that many are probably seeking. Data insertions will be rejected if they are not of the predefined type. However, I looked into it and it would only be supported in iOS 15.xx+. For Android, I don't know. Strict tables aren't backwards compatible which means we effectively wouldn't be able to use it in WatermelonDB for years to come.

Conclusion is: WatermelonDB should define the column types, even if they aren't enforced. The affinity helps inform insertions and comprehension of data. It does require some effort, but if you make migrations **without** using the built-in createTable() functionality, you can define the affinity types yourself and get these benefits. Unfortunately, raw SQL migrations aren't supported in 0.24.0 - it's still in a patch version that's yet to be fully released. So you'll have to get creative with your migrations if you truly want column 'types' for v0.24.0.
