### ISSUE TITLE
Number columns only return 0 if database is edited externally

### ISSUE THREAD

**Issue by cjx3711** [Nozbe/WatermelonDB#965]
I've been spending the past few days trying to figure this out, but for some reason, if I use an external application to update the column data, it seems to work fine for string columns, but it doesn't work for number columns.

I'm running android and I'm using Android Studio to extract the database to modify it. When I look at the rows, they contain the exact same data.
![image](https://user-images.githubusercontent.com/1100695/110758646-b2fc3100-8287-11eb-890c-d385aa6f7134.png)
For example in this image, when I get `collection[0].idx` I get back `1` but when I try `collection[1].idx` I get `0`.

The underlying data is exactly the same, the only difference is that I made use of watermelon to update the second row.

I am guessing there's a cache somewhere else that watermelon uses?

I need this because I plan on shipping a prepopulated database with the app and want to be able to read from a database that's edited with an external application.

**Comment by radex** [comment]
I think the external application you're using might be storing the numbers not as numbers but as strings. That will confuse WatermelonDB, because it it receives a "1.0" string, it assumes the value to be broken and changes it to number null value - 0. Check if you can force Android Studio to set the right value type
